<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <Import Project="../../../SharedConfigurations.props" />

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Legion.ADF.Messaging.Abstractions\Legion.ADF.Messaging.Abstractions.csproj" />
  </ItemGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>Legion.ADF.Messaging.Inbox.IntegrationTests.PostgreSQL</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>

	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>Legion.ADF.Messaging.Inbox.IntegrationTests.SqlServer</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>

</Project>
