<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>Latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <RootNamespace>Legion.ExpressionsSerializer</RootNamespace>
    <PackageId>Legion.ExpressionsSerializer</PackageId>
    <Description>Legion.ExpressionsSerializer</Description>
    <PackageTags></PackageTags>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageReleaseNotes></PackageReleaseNotes>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/legion-dotnet/legion</PackageProjectUrl>
    <RepositoryUrl>https://github.com/legion-dotnet/legion</RepositoryUrl>
    <PackageIcon>legion.png</PackageIcon>
    <NeutralLanguage>en</NeutralLanguage>
    <Copyright>Copyright LEGION</Copyright>
    <Authors>Tomas Pilat</Authors>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Legion\Legion.csproj" />
  </ItemGroup>

</Project>