using Legion.Database.Metamodel;
using Legion.Validation;

namespace Legion.Database.Internal;

public class Column : IColumn, IValidable
{
	[Newtonsoft.Json.JsonIgnore]
#if NET6_0_OR_GREATER
	[System.Text.Json.Serialization.JsonIgnore]
#endif
	[System.Xml.Serialization.XmlIgnore]
	private Table _table;

	[Newtonsoft.Json.JsonIgnore]
#if NET6_0_OR_GREATER
	[System.Text.Json.Serialization.JsonIgnore]
#endif
	[System.Xml.Serialization.XmlIgnore]
	private View _view;

	[Newtonsoft.Json.JsonIgnore]
#if NET6_0_OR_GREATER
	[System.Text.Json.Serialization.JsonIgnore]
#endif
	[System.Xml.Serialization.XmlIgnore]
	private PrimaryKey? _primaryKey;

	[Newtonsoft.Json.JsonIgnore]
#if NET6_0_OR_GREATER
	[System.Text.Json.Serialization.JsonIgnore]
#endif
	[System.Xml.Serialization.XmlIgnore]
	private List<UniqueConstraint> _uniqueConstraints;

	[Newtonsoft.Json.JsonIgnore]
#if NET6_0_OR_GREATER
	[System.Text.Json.Serialization.JsonIgnore]
#endif
	[System.Xml.Serialization.XmlIgnore]
	private List<Index> _indexes;

	[Newtonsoft.Json.JsonIgnore]
#if NET6_0_OR_GREATER
	[System.Text.Json.Serialization.JsonIgnore]
#endif
	[System.Xml.Serialization.XmlIgnore]
	private ForeignKey? _targetForeignKey;

	[Newtonsoft.Json.JsonIgnore]
#if NET6_0_OR_GREATER
	[System.Text.Json.Serialization.JsonIgnore]
#endif
	[System.Xml.Serialization.XmlIgnore]
	private List<ForeignKey> _sourceForeignKeys;

	public string Name { get; set; }

	public int OrdinalPosition { get; set; }
	public string DatabaseType { get; set; }
	public bool IsNotNull { get; set; }
	public string? DefaultValue { get; set; }
	public Type CsharpType { get; set; }
	public int CharacterMaximumLength { get; set; }
	public int? Precision { get; set; }
	public int? Scale { get; set; }
	public bool IsIdentity { get; set; }
	public long? IdentityStart { get; set; }
	public long? IdentityIncrement { get; set; }
	public long? LastIdentity { get; set; }
	public string? ComputedColumnSql { get; set; }
	public bool IsSingleUniqueConstraint { get; set; }
	public bool IsMultiUniqueConstraint { get; set; }

	/// <summary>
	///     Indicates when values will be generated by the database for this column, or <c>null</c> if
	///     the database will not generate values.
	/// </summary>
	public ValueGenerated? ValueGenerated { get; set; }
	public bool IsPrimaryKey { get; internal set; }

	[Newtonsoft.Json.JsonIgnore]
#if NET6_0_OR_GREATER
	[System.Text.Json.Serialization.JsonIgnore]
#endif
	[System.Xml.Serialization.XmlIgnore]
	public ITable Table => _table;

	[Newtonsoft.Json.JsonIgnore]
#if NET6_0_OR_GREATER
	[System.Text.Json.Serialization.JsonIgnore]
#endif
	[System.Xml.Serialization.XmlIgnore]
	public IView View => _view;

	[Newtonsoft.Json.JsonIgnore]
#if NET6_0_OR_GREATER
	[System.Text.Json.Serialization.JsonIgnore]
#endif
	[System.Xml.Serialization.XmlIgnore]
	IPrimaryKey? IColumn.PrimaryKey => _primaryKey;

	[Newtonsoft.Json.JsonIgnore]
#if NET6_0_OR_GREATER
	[System.Text.Json.Serialization.JsonIgnore]
#endif
	[System.Xml.Serialization.XmlIgnore]
	IEnumerable<IUniqueConstraint> IColumn.UniqueConstraints => _uniqueConstraints;

	[Newtonsoft.Json.JsonIgnore]
#if NET6_0_OR_GREATER
	[System.Text.Json.Serialization.JsonIgnore]
#endif
	[System.Xml.Serialization.XmlIgnore]
	IEnumerable<IIndex> IColumn.Indexes => _indexes;

	[Newtonsoft.Json.JsonIgnore]
#if NET6_0_OR_GREATER
	[System.Text.Json.Serialization.JsonIgnore]
#endif
	[System.Xml.Serialization.XmlIgnore]
	IForeignKey? IColumn.TargetForeignKey => _targetForeignKey;

	[Newtonsoft.Json.JsonIgnore]
#if NET6_0_OR_GREATER
	[System.Text.Json.Serialization.JsonIgnore]
#endif
	[System.Xml.Serialization.XmlIgnore]
	IEnumerable<IForeignKey> IColumn.SourceForeignKeys => _sourceForeignKeys;

	public Column()
	{
		_uniqueConstraints = [];
		_indexes = [];
		_sourceForeignKeys = [];
	}

	private bool built;
	public bool Build(Table table)
	{
		if (built)
			return false;

		Throw.IfArgumentNull(table);

		built = true;

		_table = table;

		return true;
	}

	public bool Build(View view)
	{
		if (built)
			return false;

		Throw.IfArgumentNull(view);

		built = true;

		_view = view;

		return true;
	}

	internal Column SetPrimaryKey(PrimaryKey primaryKey)
	{
		Throw.IfArgumentNull(primaryKey);

		_primaryKey = primaryKey;
		return this;
	}

	internal Column AddUniqueConstraint(UniqueConstraint uniqueConstraint)
	{
		Throw.IfArgumentNull(uniqueConstraint);

		_uniqueConstraints ??= [];
		_uniqueConstraints.Add(uniqueConstraint);
		return this;
	}

	internal Column AddIndex(Index index)
	{
		Throw.IfArgumentNull(index);

		_indexes ??= [];
		_indexes.Add(index);
		return this;
	}

	internal Column SetTargetForeignKey(ForeignKey foreignKey)
	{
		Throw.IfArgumentNull(foreignKey);

		_targetForeignKey = foreignKey;
		return this;
	}

	internal Column AddSourceForeignKey(ForeignKey foreignKey)
	{
		Throw.IfArgumentNull(foreignKey);

		_sourceForeignKeys ??= [];
		_sourceForeignKeys.Add(foreignKey);
		return this;
	}

	public static void SetValidatorRules(
		ValidatorBuilder<Column> builder,
		Dictionary<string, object>? globalValidationState = null,
		Dictionary<string, object>? localValidationState = null)
	{
		builder
			.ForProperty(x => x.Name, v => v.NotDefaultOrWhiteSpace())
			.ForProperty(x => x.DatabaseType, v => v.NotDefaultOrWhiteSpace())
		;
	}

	public IValidationResult Validate(Dictionary<string, object>? globalValidationState = null)
	{
		var builder = new ValidatorBuilder<Column>();
		SetValidatorRules(builder, globalValidationState, localValidationState: null);
		var validator = builder.Build();

		return validator.Validate(this);
	}

	public Column Clone()
		=> new()
		{
			Name = Name,
			OrdinalPosition = OrdinalPosition,
			DatabaseType = DatabaseType,
			IsNotNull = IsNotNull,
			DefaultValue = DefaultValue,
			CsharpType = CsharpType,
			CharacterMaximumLength = CharacterMaximumLength,
			Precision = Precision,
			Scale = Scale,
			IsIdentity = IsIdentity,
			IdentityStart = IdentityStart,
			IdentityIncrement = IdentityIncrement,
			LastIdentity = LastIdentity,
			ComputedColumnSql = ComputedColumnSql,
			IsSingleUniqueConstraint = IsSingleUniqueConstraint,
			IsMultiUniqueConstraint = IsMultiUniqueConstraint,
			IsPrimaryKey = IsPrimaryKey,
			ValueGenerated = ValueGenerated
		};

	public override string? ToString()
	{
		return Name;
	}
}
