<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;netstandard2.0</TargetFrameworks>
    <LangVersion>12.0</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <RootNamespace>Legion</RootNamespace>
    <PackageId>Legion</PackageId>
    <Description>Legion</Description>
    <PackageTags></PackageTags>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageReleaseNotes></PackageReleaseNotes>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/legion-dotnet/legion</PackageProjectUrl>
    <RepositoryUrl>https://github.com/legion-dotnet/legion</RepositoryUrl>
    <PackageIcon>legion.png</PackageIcon>
    <NeutralLanguage>en</NeutralLanguage>
    <Copyright>Copyright LEGION</Copyright>
    <Authors>Tomas Pilat</Authors>
  </PropertyGroup>

  <Import Project="../../SharedConfigurations.props" />

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\legion.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="8.0.5" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <None Update="ResourcesGenerator\ResourceDataGenerator.tt">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>ResourceDataGenerator.cs</LastGenOutput>
    </None>
    <None Update="ResourcesGenerator\ResourcesGenerator.tt">
      <Generator>TextTemplatingFilePreprocessor</Generator>
      <LastGenOutput>ResourcesGenerator.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="ResourcesGenerator\ResourceDataGenerator.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ResourceDataGenerator.tt</DependentUpon>
    </Compile>
    <Compile Update="ResourcesGenerator\ResourcesGenerator.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ResourcesGenerator.tt</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
