<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>Latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <RootNamespace>Legion.AspNetCore</RootNamespace>
    <PackageId>Legion.AspNetCore</PackageId>
    <Description>Legion.AspNetCore</Description>
    <PackageTags></PackageTags>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageReleaseNotes></PackageReleaseNotes>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/legion-dotnet/legion</PackageProjectUrl>
    <RepositoryUrl>https://github.com/legion-dotnet/legion</RepositoryUrl>
    <PackageIcon>legion.png</PackageIcon>
    <NeutralLanguage>en</NeutralLanguage>
    <Copyright>Copyright LEGION</Copyright>
    <Authors>Tomas Pilat</Authors>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <Import Project="../../SharedConfigurations.props" />

  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\legion.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.4" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="8.1.4" />
    <PackageReference Include="Swashbuckle.AspNetCore.Filters" Version="8.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Legion\Legion.csproj" />
  </ItemGroup>

</Project>
