<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <Import Project="../../../SharedConfigurations.props" />

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Legion.Database.PostgreSQL\Legion.Database.PostgreSQL.csproj" />
    <ProjectReference Include="..\..\..\src\Legion.EntityFrameworkCore.PostgreSQL\Legion.EntityFrameworkCore.PostgreSQL.csproj" />
    <ProjectReference Include="..\Legion.ADF.ServiceBus.Jobs\Legion.ADF.ServiceBus.Jobs.csproj" />
  </ItemGroup>

</Project>
