// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Legion.Generators.AppGen.AppGenGenerators.Model
{
    using Legion.Extensions;
    using Legion.Generators.AppGen.Model;
    using Legion.Generators.AppGen.Descriptors;
    using Legion.Generators.AppGen.Descriptors.MetaDescriptors;
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\BaseQueryEntityGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class BaseQueryEntityGenerator : Generator.GeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 12 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\BaseQueryEntityGenerator.tt"

	SetGenerationEnvironment(this.GenerationEnvironment);
	
	BaseQueryEntityDescriptor entityBaseDesc = GetParam<BaseQueryEntityDescriptor>("BaseQueryEntityDescriptor");
	string modelName = GetParam<string>("modelName");
	string contextName = GetParam<string>("contextName");

	StartNewFile(entityBaseDesc.TargetFolder(modelName, contextName), entityBaseDesc.FileName);
	
	foreach (string import in entityBaseDesc.Imports)
	{

            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 24 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\BaseQueryEntityGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(import));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 25 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\BaseQueryEntityGenerator.tt"

	}
	if (0 < entityBaseDesc.Imports.Count)
	{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 31 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\BaseQueryEntityGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 34 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\BaseQueryEntityGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityBaseDesc.Namespace(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\npublic abstract class ");
            
            #line 36 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\BaseQueryEntityGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityBaseDesc.Name));
            
            #line default
            #line hidden
            this.Write(" : Legion.Model.IQueryEntity\r\n{\r\n}\r\n");
            
            #line 39 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\BaseQueryEntityGenerator.tt"

	Process();

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
