// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Legion.Generators.AppGen.AppGenGenerators.Model
{
    using Legion.Extensions;
    using Legion.Generators.AppGen.Model;
    using Legion.Generators.AppGen.Descriptors;
    using Legion.Generators.AppGen.Descriptors.MetaDescriptors;
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class EntityEqualityComparerGenerator : Generator.GeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 12 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"

	SetGenerationEnvironment(this.GenerationEnvironment);
	
	EntityModelDescriptor entityDesc = GetParam<EntityModelDescriptor>("EntityModelDescriptor");
	string modelName = GetParam<string>("modelName");
	string contextName = GetParam<string>("contextName");

	StartNewFile(entityDesc.EntityEqualityComparerTargetFolder, entityDesc.EntityEqualityComparerFileName);
	
	string @sealed = entityDesc.Data.IsSealed ? " sealed" : "";
	string iAuditEntry = entityDesc.Data.IsAuditEntry ? ", Legion.Model.Audit.IAuditEntry" : "";
	string iSelfAuditableEntity = entityDesc.Data.IsSelfAuditableEntity ? ", Legion.Model.Audit.ISelfAuditableEntity" : "";
	string iAuditableEntity = entityDesc.Data.IsAuditableEntity ? ", Legion.Model.Audit.IAuditableEntity" : "";
	string iSynchronizable = entityDesc.Data.IsSynchronizableEntity ? ", Legion.Model.Synchronyzation.ISynchronizable" : "";
	string iCorrelable = entityDesc.Data.IsCorrelableEntity ? ", Legion.Model.Correlation.ICorrelable" : "";
	string customInterfaces = string.IsNullOrWhiteSpace(entityDesc.Data.CustomInterfaces) ? "" : ", " + entityDesc.Data.CustomInterfaces;
	
	var concurrencyProps = entityDesc.Data.Properties.Where(x => x.IsConcurrencyToken).ToList();
	var concurrencyProp = concurrencyProps.Count == 1 ? concurrencyProps.First() : null;
	string iConcurrent = (concurrencyProp != null) ? ", Legion.Model.Concurrence.IConcurrent" : "";

	foreach (string import in entityDesc.EntityEqualityComparerImports)
	{

            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 36 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(import));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 37 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"

	}
	if (0 < entityDesc.EntityEqualityComparerImports.Count)
	{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 43 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 46 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Namespace(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\npublic");
            
            #line 48 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(@sealed));
            
            #line default
            #line hidden
            this.Write(" partial class ");
            
            #line 48 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Name));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 48 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.GetBaseEntityName(modelName, contextName)));
            
            #line default
            #line hidden
            
            #line 48 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(iAuditEntry));
            
            #line default
            #line hidden
            
            #line 48 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(iSelfAuditableEntity));
            
            #line default
            #line hidden
            
            #line 48 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(iSynchronizable));
            
            #line default
            #line hidden
            
            #line 48 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(iConcurrent));
            
            #line default
            #line hidden
            
            #line 48 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(iCorrelable));
            
            #line default
            #line hidden
            
            #line 48 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(customInterfaces));
            
            #line default
            #line hidden
            
            #line 48 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(iAuditableEntity));
            
            #line default
            #line hidden
            this.Write(", Legion.Model.IEntity\r\n{\r\n\tpublic bool EqualsTo(\r\n\t\t");
            
            #line 51 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write("? obj,\r\n\t\tComparisonOptions comparisonOptions = ComparisonOptions.CompareAll,\r\n\t\t" +
                    "Action<ComparisonConditions<");
            
            #line 53 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(">>? conditions = null)\r\n\t\t=> ");
            
            #line 54 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.ComparerName));
            
            #line default
            #line hidden
            this.Write(".EqualsTo(\r\n\t\t\tthis,\r\n\t\t\tobj,\r\n\t\t\tcomparisonOptions,\r\n\t\t\tconditions,\r\n\t\t\tcache: n" +
                    "ull);\r\n\r\n\tpublic");
            
            #line 61 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(@sealed));
            
            #line default
            #line hidden
            this.Write(" partial class ");
            
            #line 61 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.ComparerName));
            
            #line default
            #line hidden
            this.Write(" : IEqualityComparer<");
            
            #line 61 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Name));
            
            #line default
            #line hidden
            this.Write(">\r\n\t{\r\n\t\tpublic static bool EqualsTo(\r\n\t\t\t");
            
            #line 64 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write("? obj1,\r\n\t\t\t");
            
            #line 65 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write("? obj2,\r\n\t\t\tComparisonOptions comparisonOptions = ComparisonOptions.CompareAll,\r\n" +
                    "\t\t\tAction<ComparisonConditions<");
            
            #line 67 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(@">>? conditions = null,
			Dictionary<object, HashSet<object>>? cache = null)
		{
			if (obj1 == null && obj2 == null)
				return true;

			if (obj1 == null || obj2 == null)
				return false;

			if (ReferenceEquals(obj1, obj2))
				return true;

			cache ??= [];

			cache.TryGetValue(obj1, out HashSet<object>? cachedHashSet);
			if (cachedHashSet?.Contains(obj2) == true)
				return true;
			
			ComparisonConditions<");
            
            #line 85 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(">? conds = null;\r\n\t\t\r\n\t\t\tif ((ComparisonOptions.CompareProperties & comparisonOpt" +
                    "ions) == ComparisonOptions.CompareProperties)\r\n\t\t\t{\r\n\t\t\t\tif (conditions != null)" +
                    "\r\n\t\t\t\t{\r\n\t\t\t\t\tconds = new ComparisonConditions<");
            
            #line 91 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(">();\r\n\t\t\t\t\tconditions.Invoke(conds);\r\n");
            
            #line 93 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"

	if (entityDesc.Data.ConvertEntity != ConvertEntity.ToEnumerationClass
		&& entityDesc.Data.ConvertEntity != ConvertEntity.ToEnumAndEnumerationClass)
	{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 99 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"

		foreach (var property in entityDesc.Properties)
		{
			var notEquals = property.ClrType == typeof(string)
				? $"!string.Equals(obj1.{property.Name}, obj2.{property.Name})"
				: $"obj1.{property.Name} != obj2.{property.Name}";

			if (property.IsArray())
				notEquals = $"(obj1.{property.Name} != null || obj2.{property.Name} != null) && (obj1.{property.Name} == null || obj2.{property.Name} == null || !obj1.{property.Name}.SequenceEqual(obj2.{property.Name}))";
			else if (property.IsCollection())
				notEquals = $"(obj1.{property.Name} != null || obj2.{property.Name} != null) && (obj1.{property.Name} == null || obj2.{property.Name} == null || !obj1.{property.Name}.SequenceEqual(obj2.{property.Name}))";

            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tif (conds.CanCompare(obj1, nameof(obj1.");
            
            #line 111 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(")) && ");
            
            #line 111 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(notEquals));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\treturn false;\r\n");
            
            #line 113 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"

		}

            
            #line default
            #line hidden
            this.Write("\t\t\t\t}\r\n\t\t\t\telse\r\n\t\t\t\t{\r\n");
            
            #line 119 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"

		foreach (var property in entityDesc.Properties)
		{
			var notEquals = property.ClrType == typeof(string)
				? $"!string.Equals(obj1.{property.Name}, obj2.{property.Name})"
				: $"obj1.{property.Name} != obj2.{property.Name}";

			if (property.IsArray())
				notEquals = $"(obj1.{property.Name} != null || obj2.{property.Name} != null) && (obj1.{property.Name} == null || obj2.{property.Name} == null || !obj1.{property.Name}.SequenceEqual(obj2.{property.Name}))";
			else if (property.IsCollection())
				notEquals = $"(obj1.{property.Name} != null || obj2.{property.Name} != null) && (obj1.{property.Name} == null || obj2.{property.Name} == null || !obj1.{property.Name}.SequenceEqual(obj2.{property.Name}))";

            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tif (");
            
            #line 131 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(notEquals));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\treturn false;\r\n");
            
            #line 133 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"

		}
	}

            
            #line default
            #line hidden
            this.Write("\t\t\t\t}\r\n\t\t\t}\r\n\r\n\t\t\tif (cachedHashSet == null)\r\n\t\t\t{\r\n\t\t\t\tcachedHashSet = [];\r\n\t\t\t\t" +
                    "cache[obj1] = cachedHashSet;\r\n\t\t\t}\r\n\r\n\t\t\tcachedHashSet.Add(obj2);\r\n");
            
            #line 147 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"

	var targetNavigationEntities = new List<EntityModelDescriptor>();
	foreach (var navigation in entityDesc.Navigations.Where(n => !n.Data.Ignore && n.Data.TargetType.ModelContextNames.ContainsKey(modelName)))
	{
		var targetEntityDesc = entityDesc.Context.GetEntityModelDescriptor(navigation.Data.TargetType, true, modelName, contextName);
		if (targetEntityDesc != null)
			targetNavigationEntities.Add(targetEntityDesc);
	}

	var targetBackNavigationEqualityComparers = new List<EntityModelDescriptor>();
	foreach (var navigation in entityDesc.BackNavigations.Where(bn => !bn.Data.Ignore && bn.Data.TargetType.ModelContextNames.ContainsKey(modelName)))
	{
		var targetEntityDesc = entityDesc.Context.GetEntityModelDescriptor(navigation.Data.TargetType, true, modelName, contextName);
		if (targetEntityDesc != null)
			targetBackNavigationEqualityComparers.Add(targetEntityDesc);
	}

	if (0 < targetNavigationEntities.Count || 0 < targetBackNavigationEqualityComparers.Count)
	{

            
            #line default
            #line hidden
            this.Write("\r\n\t\t\tif ((ComparisonOptions.CompareReferences & comparisonOptions) == ComparisonO" +
                    "ptions.CompareReferences)\r\n\t\t\t{\r\n");
            
            #line 170 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"

		foreach (var navigation in entityDesc.Navigations.Where(n => !n.Data.Ignore && n.Data.TargetType.ModelContextNames.ContainsKey(modelName)))
		{
			var targetEntityDesc = entityDesc.Context.GetEntityModelDescriptor(navigation.Data.TargetType, true, modelName, contextName);
			if (targetEntityDesc != null)
			{

            
            #line default
            #line hidden
            this.Write("\t\t\t\tif (!");
            
            #line 177 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(targetEntityDesc.Name));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 177 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(targetEntityDesc.Name));
            
            #line default
            #line hidden
            this.Write("EqualityComparer.EqualsTo(obj1.");
            
            #line 177 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Name));
            
            #line default
            #line hidden
            this.Write(", obj2.");
            
            #line 177 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Name));
            
            #line default
            #line hidden
            this.Write(", comparisonOptions, conds?.GetConditions(x => x.");
            
            #line 177 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Name));
            
            #line default
            #line hidden
            this.Write("), cache))\r\n\t\t\t\t\treturn false;\r\n");
            
            #line 179 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"

			}
		}
		
		foreach (var navigation in entityDesc.BackNavigations.Where(bn => !bn.Data.Ignore && bn.Data.TargetType.ModelContextNames.ContainsKey(modelName)))
		{
			var targetEntityDesc = entityDesc.Context.GetEntityModelDescriptor(navigation.Data.TargetType, true, modelName, contextName);
			if (targetEntityDesc != null)
			{
				if (navigation.Data.IsCollection)
				{

            
            #line default
            #line hidden
            this.Write("\t\t\t\tif (!ComparisonHelper.SequenceEqual(obj1.");
            
            #line 191 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Name));
            
            #line default
            #line hidden
            this.Write(", obj2.");
            
            #line 191 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Name));
            
            #line default
            #line hidden
            this.Write(", new ");
            
            #line 191 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(targetEntityDesc.Name));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 191 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(targetEntityDesc.Name));
            
            #line default
            #line hidden
            this.Write("EqualityComparer(comparisonOptions, conds?.GetConditions(x => x.");
            
            #line 191 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Name));
            
            #line default
            #line hidden
            this.Write("), cache)))\r\n\t\t\t\t\treturn false;\r\n");
            
            #line 193 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"

				}
				else
				{

            
            #line default
            #line hidden
            this.Write("\t\t\t\tif (!");
            
            #line 198 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(targetEntityDesc.Name));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 198 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(targetEntityDesc.Name));
            
            #line default
            #line hidden
            this.Write("EqualityComparer.EqualsTo(obj1.");
            
            #line 198 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Name));
            
            #line default
            #line hidden
            this.Write(", obj2.");
            
            #line 198 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Name));
            
            #line default
            #line hidden
            this.Write(", comparisonOptions, conds?.GetConditions(x => x.");
            
            #line 198 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Name));
            
            #line default
            #line hidden
            this.Write("), cache))\r\n\t\t\t\t\treturn false;\r\n");
            
            #line 200 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"

				}
			}
		}

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n");
            
            #line 206 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("\r\n\t\t\treturn true;\r\n\t\t}\r\n\r\n\t\tpublic static int GetHashCode(\r\n\t\t\t");
            
            #line 214 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write("? obj,\r\n\t\t\tComparisonOptions comparisonOptions = ComparisonOptions.CompareAll,\r\n\t" +
                    "\t\tAction<ComparisonConditions<");
            
            #line 216 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(@">>? conditions = null,
			HashSet<object>? cache = null)
		{
			if (obj == null)
				return 0;

			cache ??= [];

			if (cache.Contains(obj))
				return 0;

				var hash = 1;
			return hash;
		}

		public ComparisonOptions ComparisonOptions { get; }
		public Action<ComparisonConditions<");
            
            #line 232 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(">>? Conditions { get; }\r\n\t\tpublic Dictionary<object, HashSet<object>>? Cache { ge" +
                    "t; }\r\n\t\r\n\t\tpublic ");
            
            #line 235 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.ComparerName));
            
            #line default
            #line hidden
            this.Write("(\r\n\t\t\tComparisonOptions comparisonOptions = ComparisonOptions.CompareAll,\r\n\t\t\tAct" +
                    "ion<ComparisonConditions<");
            
            #line 237 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(">>? conditions = null,\r\n\t\t\tDictionary<object, HashSet<object>>? cache = null)\r\n\t\t" +
                    "{\r\n\t\t\tCache = cache ?? [];\r\n\t\t\tComparisonOptions = comparisonOptions;\r\n\t\t\tCondit" +
                    "ions = conditions;\r\n\t\t}\r\n\t\r\n\t\tpublic bool Equals(\r\n\t\t\t");
            
            #line 246 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write("? obj1,\r\n\t\t\t");
            
            #line 247 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write("? obj2)\r\n\t\t\t=> EqualsTo(\r\n\t\t\t\tobj1,\r\n\t\t\t\tobj2,\r\n\t\t\t\tComparisonOptions,\r\n\t\t\t\tCondi" +
                    "tions,\r\n\t\t\t\tCache);\r\n\t\r\n\t\tpublic int GetHashCode([DisallowNull] ");
            
            #line 255 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write("? obj)\r\n\t\t\t=> GetHashCode(\r\n\t\t\t\tobj,\r\n\t\t\t\tComparisonOptions,\r\n\t\t\t\tConditions,\r\n\t\t" +
                    "\t\tcache: null);\r\n\t}\r\n}\r\n");
            
            #line 263 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityEqualityComparerGenerator.tt"

	Process();

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
