// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Legion.Generators.AppGen.AppGenGenerators.Model
{
    using Legion.Extensions;
    using Legion.Generators.AppGen.Model;
    using Legion.Generators.AppGen.Descriptors;
    using Legion.Generators.AppGen.Descriptors.MetaDescriptors;
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class EntityMapperGenerator : Generator.GeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 12 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"

	SetGenerationEnvironment(this.GenerationEnvironment);
	
	EntityModelDescriptor entityDesc = GetParam<EntityModelDescriptor>("EntityModelDescriptor");
	string modelName = GetParam<string>("modelName");
	string contextName = GetParam<string>("contextName");

	StartNewFile(entityDesc.EntityMapperTargetFolder, entityDesc.EntityMapperFileName);
	
	string @sealed = entityDesc.Data.IsSealed ? " sealed" : "";
	string iAuditEntry = entityDesc.Data.IsAuditEntry ? ", Legion.Model.Audit.IAuditEntry" : "";
	string iSelfAuditableEntity = entityDesc.Data.IsSelfAuditableEntity ? ", Legion.Model.Audit.ISelfAuditableEntity" : "";
	string iAuditableEntity = entityDesc.Data.IsAuditableEntity ? ", Legion.Model.Audit.IAuditableEntity" : "";
	string iSynchronizable = entityDesc.Data.IsSynchronizableEntity ? ", Legion.Model.Synchronyzation.ISynchronizable" : "";
	string iCorrelable = entityDesc.Data.IsCorrelableEntity ? ", Legion.Model.Correlation.ICorrelable" : "";
	string customInterfaces = string.IsNullOrWhiteSpace(entityDesc.Data.CustomInterfaces) ? "" : ", " + entityDesc.Data.CustomInterfaces;
	
	var concurrencyProps = entityDesc.Data.Properties.Where(x => x.IsConcurrencyToken).ToList();
	var concurrencyProp = concurrencyProps.Count == 1 ? concurrencyProps.First() : null;
	string iConcurrent = (concurrencyProp != null) ? ", Legion.Model.Concurrence.IConcurrent" : "";

	foreach (string import in entityDesc.EntityMapperImports)
	{

            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 36 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(import));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 37 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"

	}
	if (0 < entityDesc.EntityMapperImports.Count)
	{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 43 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 46 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Namespace(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\npublic");
            
            #line 48 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(@sealed));
            
            #line default
            #line hidden
            this.Write(" partial class ");
            
            #line 48 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Name));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 48 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.GetBaseEntityName(modelName, contextName)));
            
            #line default
            #line hidden
            
            #line 48 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(iAuditEntry));
            
            #line default
            #line hidden
            
            #line 48 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(iSelfAuditableEntity));
            
            #line default
            #line hidden
            
            #line 48 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(iSynchronizable));
            
            #line default
            #line hidden
            
            #line 48 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(iConcurrent));
            
            #line default
            #line hidden
            
            #line 48 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(iCorrelable));
            
            #line default
            #line hidden
            
            #line 48 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(customInterfaces));
            
            #line default
            #line hidden
            
            #line 48 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(iAuditableEntity));
            
            #line default
            #line hidden
            this.Write(", Legion.Model.IEntity\r\n{\r\n\tpublic static ");
            
            #line 50 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write("? Map(\r\n\t\t");
            
            #line 51 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(" source,\r\n\t\t");
            
            #line 52 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write("? target,\r\n\t\tReferenceModifier referenceModifier = ReferenceModifier.SkipAllRefer" +
                    "ences,\r\n\t\tAction<MappingConditions<");
            
            #line 54 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(@">>? conditions = null,
		Legion.Reflection.InstanceFactory? instanceFactory = null,
		Dictionary<object, object>? cache = null)
	{
		Throw.IfArgumentNull(source);

		return source.MapTo(target, referenceModifier, conditions, instanceFactory, cache);
	}

	public ");
            
            #line 63 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write("? Clone(\r\n\t\tReferenceModifier referenceModifier = ReferenceModifier.SkipAllRefere" +
                    "nces,\r\n\t\tAction<MappingConditions<");
            
            #line 65 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(">>? conditions = null,\r\n\t\tLegion.Reflection.InstanceFactory? instanceFactory = nu" +
                    "ll,\r\n\t\tDictionary<object, object>? cache = null)\r\n\t\t=> MapTo(target: null, refer" +
                    "enceModifier, conditions, instanceFactory, cache);\r\n\r\n\tpublic ");
            
            #line 70 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write("? MapTo(\r\n\t\t");
            
            #line 71 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write("? target,\r\n\t\tReferenceModifier referenceModifier = ReferenceModifier.SkipAllRefer" +
                    "ences,\r\n\t\tAction<MappingConditions<");
            
            #line 73 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(">>? conditions = null,\r\n\t\tLegion.Reflection.InstanceFactory? instanceFactory = nu" +
                    "ll,\r\n\t\tDictionary<object, object>? cache = null)\r\n\t{\r\n\t\tcache ??= [];\r\n");
            
            #line 78 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"

	if (entityDesc.Data.ConvertEntity == ConvertEntity.ToEnumerationClass
		|| entityDesc.Data.ConvertEntity == ConvertEntity.ToEnumAndEnumerationClass)
	{

            
            #line default
            #line hidden
            this.Write("\t\ttarget ??= ");
            
            #line 83 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.FullName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(".DictionaryMap.Value[");
            
            #line 83 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Data.FirstPrimaryKey.Name));
            
            #line default
            #line hidden
            this.Write("];\r\n");
            
            #line 84 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"

	}
	else
	{

            
            #line default
            #line hidden
            this.Write("\t\ttarget ??= instanceFactory?.CreateInstance<");
            
            #line 89 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.FullName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(">(\r\n\t\t\t\tuseActivatorIfNoFactoryFound: false,\r\n\t\t\t\tthrowIfFactoryReturnsNull: true" +
                    ")\r\n\t\t\t?? new ");
            
            #line 92 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.FullName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write("();\r\n");
            
            #line 93 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("\r\n\t\tif (cache.TryGetValue(this, out var cached))\r\n\t\t\treturn (");
            
            #line 98 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(")cached;\r\n\t\t\t\r\n\t\tMappingConditions<");
            
            #line 100 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(">? conds = null;\r\n\t\tif (conditions != null)\r\n\t\t{\r\n\t\t\tconds = new MappingCondition" +
                    "s<");
            
            #line 103 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(">();\r\n\t\t\tconditions.Invoke(conds);\r\n");
            
            #line 105 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"

	if (entityDesc.Data.ConvertEntity != ConvertEntity.ToEnumerationClass
		&& entityDesc.Data.ConvertEntity != ConvertEntity.ToEnumAndEnumerationClass)
	{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 111 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"

		foreach (var property in entityDesc.Properties)
		{
			var isArray = property.IsArray();
			var isCollection = property.IsCollection();
			var collectionCopy = isCollection && !isArray
				? "?.ToList()"
				: (isArray ? "?.ToArray()" : "");

            
            #line default
            #line hidden
            this.Write("\t\t\tif (conds.CanMap(this, nameof(");
            
            #line 120 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(")))\r\n\t\t\t\ttarget.");
            
            #line 121 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 121 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            
            #line 121 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(collectionCopy));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 122 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"

		}

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\t\telse\r\n\t\t{\r\n");
            
            #line 128 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"

		foreach (var property in entityDesc.Properties)
		{
			var isArray = property.IsArray();
			var isCollection = property.IsCollection();
			var collectionCopy = isCollection && !isArray
				? "?.ToList()"
				: (isArray ? "?.ToArray()" : "");

            
            #line default
            #line hidden
            this.Write("\t\t\ttarget.");
            
            #line 137 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 137 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            
            #line 137 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(collectionCopy));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 138 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"

		}
	}

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n\t\tcache.Add(this, target);\r\n");
            
            #line 145 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"

	var targetNavigationEntities = new List<EntityModelDescriptor>();
	foreach (var navigation in entityDesc.Navigations.Where(n => !n.Data.Ignore && n.Data.TargetType.ModelContextNames.ContainsKey(modelName)))
	{
		var targetEntityDesc = entityDesc.Context.GetEntityModelDescriptor(navigation.Data.TargetType, true, modelName, contextName);
		if (targetEntityDesc != null)
			targetNavigationEntities.Add(targetEntityDesc);
	}

	var targetBackNavigationMappers = new List<EntityModelDescriptor>();
	foreach (var navigation in entityDesc.BackNavigations.Where(bn => !bn.Data.Ignore && bn.Data.TargetType.ModelContextNames.ContainsKey(modelName)))
	{
		var targetEntityDesc = entityDesc.Context.GetEntityModelDescriptor(navigation.Data.TargetType, true, modelName, contextName);
		if (targetEntityDesc != null)
			targetBackNavigationMappers.Add(targetEntityDesc);
	}

	if (0 < targetNavigationEntities.Count || 0 < targetBackNavigationMappers.Count)
	{

            
            #line default
            #line hidden
            this.Write("\r\n\t\tif (referenceModifier == ReferenceModifier.MapAllReferences)\r\n\t\t{\r\n");
            
            #line 168 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"

		foreach (var navigation in entityDesc.Navigations.Where(n => !n.Data.Ignore && n.Data.TargetType.ModelContextNames.ContainsKey(modelName)))
		{
			var targetEntityDesc = entityDesc.Context.GetEntityModelDescriptor(navigation.Data.TargetType, true, modelName, contextName);
			if (targetEntityDesc != null)
			{

            
            #line default
            #line hidden
            this.Write("\t\t\ttarget.");
            
            #line 175 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 175 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Name));
            
            #line default
            #line hidden
            this.Write("?.MapTo(target.");
            
            #line 175 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Name));
            
            #line default
            #line hidden
            this.Write(", referenceModifier, conds?.GetConditions(x => x.");
            
            #line 175 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Name));
            
            #line default
            #line hidden
            this.Write("), instanceFactory, cache)!;\r\n");
            
            #line 176 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"

			}
		}
		
		foreach (var navigation in entityDesc.BackNavigations.Where(bn => !bn.Data.Ignore && bn.Data.TargetType.ModelContextNames.ContainsKey(modelName)))
		{
			var targetEntityDesc = entityDesc.Context.GetEntityModelDescriptor(navigation.Data.TargetType, true, modelName, contextName);
			if (targetEntityDesc != null)
			{
				if (navigation.Data.IsCollection)
				{

            
            #line default
            #line hidden
            this.Write("\t\t\ttarget._");
            
            #line 188 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.AsFieldName));
            
            #line default
            #line hidden
            this.Write(" = MapperHelper.MapToList(");
            
            #line 188 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Name));
            
            #line default
            #line hidden
            this.Write(", target._");
            
            #line 188 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.AsFieldName));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 188 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(targetEntityDesc.FullName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(".Map, referenceModifier, conds?.GetConditions(x => x.");
            
            #line 188 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Name));
            
            #line default
            #line hidden
            this.Write("), instanceFactory, cache)!;\r\n");
            
            #line 189 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"

				}
				else
				{

            
            #line default
            #line hidden
            this.Write("\t\t\ttarget.");
            
            #line 194 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 194 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Name));
            
            #line default
            #line hidden
            this.Write("?.MapTo(target.");
            
            #line 194 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(targetEntityDesc.FullName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(", referenceModifier, conds?.GetConditions(x => x.");
            
            #line 194 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Name));
            
            #line default
            #line hidden
            this.Write("), instanceFactory, cache)!;\r\n");
            
            #line 195 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"

				}
			}
		}

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\t\telse if (referenceModifier == ReferenceModifier.SetNull)\r\n\t\t{\r\n");
            
            #line 203 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"

		foreach (var navigation in entityDesc.Navigations.Where(n => !n.Data.Ignore && n.Data.TargetType.ModelContextNames.ContainsKey(modelName)))
		{
			var targetEntityDesc = entityDesc.Context.GetEntityModelDescriptor(navigation.Data.TargetType, true, modelName, contextName);
			if (targetEntityDesc != null)
			{

            
            #line default
            #line hidden
            this.Write("\t\t\ttarget.");
            
            #line 210 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Name));
            
            #line default
            #line hidden
            this.Write(" = null!;\r\n");
            
            #line 211 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"

			}
		}
		foreach (var navigation in entityDesc.BackNavigations.Where(bn => !bn.Data.Ignore && bn.Data.TargetType.ModelContextNames.ContainsKey(modelName)))
		{
			var targetEntityDesc = entityDesc.Context.GetEntityModelDescriptor(navigation.Data.TargetType, true, modelName, contextName);
			if (targetEntityDesc != null)
			{
				if (navigation.Data.IsCollection)
				{

            
            #line default
            #line hidden
            this.Write("\t\t\ttarget._");
            
            #line 222 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.AsFieldName));
            
            #line default
            #line hidden
            this.Write(" = [];\r\n");
            
            #line 223 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"

				}
				else
				{

            
            #line default
            #line hidden
            this.Write("\t\t\ttarget.");
            
            #line 228 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Name));
            
            #line default
            #line hidden
            this.Write(" = null!;\r\n");
            
            #line 229 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"

				}
			}
		}

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n");
            
            #line 235 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("\r\n\t\treturn target;\r\n\t}\r\n}\r\n");
            
            #line 242 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityMapperGenerator.tt"

	Process();

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
