// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Legion.Generators.AppGen.AppGenGenerators.Model
{
    using Legion.Extensions;
    using Legion.Generators.AppGen.Model;
    using Legion.Generators.AppGen.Descriptors;
    using Legion.Generators.AppGen.Descriptors.MetaDescriptors;
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class EntityModelEnumerationObjectGenerator : Generator.GeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 12 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"

	SetGenerationEnvironment(this.GenerationEnvironment);
	
	EntityModelEnumerationDescriptor entityDesc = GetParam<EntityModelEnumerationDescriptor>("EntityModelEnumerationDescriptor");
	string modelName = GetParam<string>("modelName");
	string contextName = GetParam<string>("contextName");

	StartNewFile(entityDesc.TargetFolder(modelName, contextName), entityDesc.EnumerationFileName);

	foreach (string import in entityDesc.Imports)
	{

            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 24 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(import));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 25 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"

	}
	if (0 < entityDesc.Imports.Count)
	{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 31 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 34 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Namespace(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\npublic partial class ");
            
            #line 36 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Name));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 36 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.GetBaseEntityName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(", Legion.Model.IEntity, IComparable\r\n{\r\n");
            
            #line 38 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"

		if (entityDesc.Data.MainColumn.ClrType != typeof(string))
		{

            
            #line default
            #line hidden
            this.Write("#pragma warning disable IDE1006 // Naming Styles\r\n");
            
            #line 43 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"

		}
		
		int commentIdx = 0;
		foreach (var enumRow in entityDesc.EnumData)
		{
			commentIdx++;
			if (1 < commentIdx)
			{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 54 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"

			}

            
            #line default
            #line hidden
            this.Write("\t/// <summary>\r\n\t/// ");
            
            #line 58 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumRow.Values[0].Replace("new Guid(\"", "").Replace("\")", "")));
            
            #line default
            #line hidden
            this.Write("\r\n\t/// </summary>\r\n\tpublic static ");
            
            #line 60 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Name));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 60 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumRow.BasePropertyCSharpName_NewObject));
            
            #line default
            #line hidden
            this.Write(" => new(");
            
            #line 60 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", enumRow.Values)));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 61 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"

		}

		if (entityDesc.Data.MainColumn.ClrType != typeof(string))
		{

            
            #line default
            #line hidden
            this.Write("#pragma warning restore IDE1006 // Naming Styles\r\n");
            
            #line 68 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"

		}

            
            #line default
            #line hidden
            this.Write("\r\n\tprivate ");
            
            #line 72 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 72 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.GetPropertiesAsMethodParameters()));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t: this()\r\n\t{\r\n");
            
            #line 75 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"

	foreach (var property in entityDesc.Properties)
	{

            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 79 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 79 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.AsFieldName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 80 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("\t}\r\n");
            
            #line 84 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"

	if (entityDesc.Data.MainColumn.ClrType == typeof(string))
	{

            
            #line default
            #line hidden
            this.Write("\r\n\tpublic override bool Equals(object? obj)\r\n\t{\r\n\t\tif (obj is not ");
            
            #line 91 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Name));
            
            #line default
            #line hidden
            this.Write(" otherValue)\r\n\t\t\treturn false;\r\n\r\n\t\tvar typeMatches = GetType().Equals(obj.GetTyp" +
                    "e());\r\n\t\tvar valueMatches = ");
            
            #line 95 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Data.MainColumn.Name));
            
            #line default
            #line hidden
            this.Write("?.Equals(otherValue.");
            
            #line 95 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Data.MainColumn.Name));
            
            #line default
            #line hidden
            this.Write(") ?? (otherValue.");
            
            #line 95 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Data.MainColumn.Name));
            
            #line default
            #line hidden
            this.Write(" == null);\r\n\r\n\t\treturn typeMatches && valueMatches;\r\n\t}\r\n\r\n\tpublic override int G" +
                    "etHashCode()\r\n\t{\r\n\t\treturn ");
            
            #line 102 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Data.MainColumn.Name));
            
            #line default
            #line hidden
            this.Write("?.GetHashCode() ?? 0;\r\n\t}\r\n\r\n\tpublic int CompareTo(object? other)\r\n\t{\r\n\t\tvar othe" +
                    "rEnumeration = other as ");
            
            #line 107 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\treturn ");
            
            #line 108 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Data.MainColumn.Name));
            
            #line default
            #line hidden
            this.Write("?.CompareTo(otherEnumeration?.");
            
            #line 108 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Data.MainColumn.Name));
            
            #line default
            #line hidden
            this.Write(") ?? 1;\r\n\t}\r\n\r\n\tpublic static ");
            
            #line 111 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Name));
            
            #line default
            #line hidden
            this.Write("? FromId(");
            
            #line 111 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.GetKeyPropertiesAsMethodParameters(entityDesc.Data.PrimaryKey)));
            
            #line default
            #line hidden
            this.Write(")\r\n\t{\r\n\t\treturn AsEnumerable_NewObjects().FirstOrDefault(x => ");
            
            #line 113 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.GetKeyPropertiesAsWhereCondition(entityDesc.Data.PrimaryKey, "x")));
            
            #line default
            #line hidden
            this.Write(");\r\n\t}\r\n\r\n\tpublic static ");
            
            #line 116 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Name));
            
            #line default
            #line hidden
            this.Write("? From");
            
            #line 116 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Data.MainColumn.Name));
            
            #line default
            #line hidden
            this.Write("(string ");
            
            #line 116 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GeneratorHelper.AsFieldName(entityDesc.Data.MainColumn.Name)));
            
            #line default
            #line hidden
            this.Write(")\r\n\t{\r\n\t\treturn AsEnumerable_NewObjects().FirstOrDefault(v => v.");
            
            #line 118 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Data.MainColumn.Name));
            
            #line default
            #line hidden
            this.Write("?.Equals(");
            
            #line 118 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GeneratorHelper.AsFieldName(entityDesc.Data.MainColumn.Name)));
            
            #line default
            #line hidden
            this.Write(", StringComparison.Ordinal) ?? false);\r\n\t}\r\n");
            
            #line 120 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"

	}
	else //NOT STRING
	{

            
            #line default
            #line hidden
            this.Write("\r\n\tpublic override bool Equals(object? obj)\r\n\t{\r\n\t\tif ((obj is not ");
            
            #line 128 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Name));
            
            #line default
            #line hidden
            this.Write(" otherValue))\r\n\t\t\treturn false;\r\n\r\n\t\tvar typeMatches = GetType().Equals(obj.GetTy" +
                    "pe());\r\n\t\tvar valueMatches = ");
            
            #line 132 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Data.MainColumn.Name));
            
            #line default
            #line hidden
            this.Write(".Equals(otherValue.");
            
            #line 132 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Data.MainColumn.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n\r\n\t\treturn typeMatches && valueMatches;\r\n\t}\r\n\r\n\tpublic override int GetHashCo" +
                    "de()\r\n\t{\r\n\t\treturn ");
            
            #line 139 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Data.MainColumn.Name));
            
            #line default
            #line hidden
            this.Write(".GetHashCode();\r\n\t}\r\n\r\n\tpublic int CompareTo(object? other)\r\n\t{\r\n\t\tvar otherEnume" +
                    "ration = other as ");
            
            #line 144 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\treturn ");
            
            #line 145 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Data.MainColumn.Name));
            
            #line default
            #line hidden
            this.Write(".CompareTo(otherEnumeration?.");
            
            #line 145 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Data.MainColumn.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n\t}\r\n\r\n\tpublic static ");
            
            #line 148 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Name));
            
            #line default
            #line hidden
            this.Write("? FromId(");
            
            #line 148 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.GetKeyPropertiesAsMethodParameters(entityDesc.Data.PrimaryKey)));
            
            #line default
            #line hidden
            this.Write(")\r\n\t{\r\n\t\treturn AsEnumerable_NewObjects().FirstOrDefault(x => ");
            
            #line 150 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.GetKeyPropertiesAsWhereCondition(entityDesc.Data.PrimaryKey, "x")));
            
            #line default
            #line hidden
            this.Write(");\r\n\t}\r\n\r\n\tpublic static ");
            
            #line 153 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Name));
            
            #line default
            #line hidden
            this.Write("? From");
            
            #line 153 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Data.MainColumn.Name));
            
            #line default
            #line hidden
            this.Write("(string ");
            
            #line 153 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GeneratorHelper.AsFieldName(entityDesc.Data.MainColumn.Name)));
            
            #line default
            #line hidden
            this.Write(")\r\n\t{\r\n\t\treturn AsEnumerable_NewObjects().FirstOrDefault(v => v.");
            
            #line 155 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Data.MainColumn.Name));
            
            #line default
            #line hidden
            this.Write(".Equals(");
            
            #line 155 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GeneratorHelper.AsFieldName(entityDesc.Data.MainColumn.Name)));
            
            #line default
            #line hidden
            this.Write("));\r\n\t}\r\n");
            
            #line 157 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("\r\n\tpublic static readonly Lazy<IReadOnlyDictionary<");
            
            #line 161 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Data.FirstPrimaryKey.CSharpType));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 161 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Name));
            
            #line default
            #line hidden
            this.Write(">> DictionaryMap = new(() => new Dictionary<");
            
            #line 161 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Data.FirstPrimaryKey.CSharpType));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 161 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Name));
            
            #line default
            #line hidden
            this.Write(">\r\n\t{\r\n");
            
            #line 163 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"

		var idx = 0;
		foreach (var enumRow in entityDesc.EnumData)
		{
			idx++;

            
            #line default
            #line hidden
            this.Write("\t\t\t{ ");
            
            #line 169 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumRow.Values[0]));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 169 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumRow.BasePropertyCSharpName_NewObject));
            
            #line default
            #line hidden
            this.Write(" }");
            
            #line 169 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(idx == entityDesc.EnumData.Count ? "" : ","));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 170 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"

		}

            
            #line default
            #line hidden
            this.Write("\t});\r\n\r\n\tpublic static IEnumerable<");
            
            #line 175 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Name));
            
            #line default
            #line hidden
            this.Write("> AsEnumerable_NewObjects()\r\n\t{\r\n");
            
            #line 177 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"

		if (entityDesc.EnumData.Count == 0)
		{

            
            #line default
            #line hidden
            this.Write("\t\tyield return null;\r\n");
            
            #line 182 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"

		}
		else
		{
			foreach (var enumRow in entityDesc.EnumData)
			{

            
            #line default
            #line hidden
            this.Write("\t\tyield return ");
            
            #line 189 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumRow.BasePropertyCSharpName_NewObject));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 190 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"

			}
		}

            
            #line default
            #line hidden
            this.Write("\t}\r\n}\r\n");
            
            #line 196 "C:\code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationObjectGenerator.tt"

	Process();

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
