// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Legion.Generators.AppGen.AppGenGenerators.Model
{
    using Legion.Extensions;
    using Legion.Generators.AppGen.Model;
    using Legion.Generators.AppGen.Descriptors;
    using Legion.Generators.AppGen.Descriptors.MetaDescriptors;
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class EntityContextGenerator : Generator.GeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 12 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"

	SetGenerationEnvironment(this.GenerationEnvironment);
	
	EntityContextDescriptor dbContextDesc = GetParam<EntityContextDescriptor>("EntityContextDescriptor");
	string modelName = GetParam<string>("modelName");
	string contextName = GetParam<string>("contextName");
	var isPostgreSql = AppGen.Model.Config.CodeGeneratorConfig.Instance.SelectedDatabaseConnection.Provider == Database.Metamodel.DatabaseProviderType.PostgreSQL;

	StartNewFile(dbContextDesc.TargetFolder(modelName, contextName), dbContextDesc.FileName);

	foreach (string import in dbContextDesc.Imports)
	{

            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 25 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(import));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 26 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"

	}
	if (0 < dbContextDesc.Imports.Count)
	{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 32 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("#nullable disable\r\n\r\nnamespace ");
            
            #line 37 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dbContextDesc.Namespace(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\npublic partial class ");
            
            #line 39 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dbContextDesc.Name));
            
            #line default
            #line hidden
            this.Write(" : Legion.EntityFrameworkCore.Audit.AuditableDbContext, ");
            
            #line 39 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dbContextDesc.AbstractionBaseNamespace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 39 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dbContextDesc.AbstractionName));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tpublic static readonly System.Collections.Generic.IReadOnlyDictionary<strin" +
                    "g, string> PrimaryKeyFormatters;\r\n\r\n\tstatic ");
            
            #line 43 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dbContextDesc.Name));
            
            #line default
            #line hidden
            this.Write("()\r\n\t{\r\n\t\tPrimaryKeyFormatters = new System.Collections.Generic.Dictionary<string" +
                    ", string>\r\n\t\t{\r\n");
            
            #line 47 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"

	foreach (var entity in dbContextDesc.Data.Entities.OrderBy(x => x.Name))
	{
		var entityDesc = dbContextDesc.Context.GetEntityModelDescriptor(entity, true, modelName, contextName);
		if (entityDesc == null || !entity.GenerateModel) continue;

            
            #line default
            #line hidden
            this.Write("\t\t\t{ nameof(");
            
            #line 53 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.FullName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write("), ");
            
            #line 53 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.EntityContextModelBuilderBaseName));
            
            #line default
            #line hidden
            this.Write(".PrimaryKeyFormatter },\r\n");
            
            #line 54 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("\t\t};\r\n\t}\r\n\r\n");
            
            #line 60 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"

	foreach (var entity in dbContextDesc.Data.Entities.OrderBy(x => x.Name))
	{
		var entityDesc = dbContextDesc.Context.GetEntityModelDescriptor(entity, true, modelName, contextName);
		if (entityDesc == null || !entity.GenerateModel) continue;
		//if (entity.IsAuditEntry) continue;

            
            #line default
            #line hidden
            this.Write("\tpublic virtual ");
            
            #line 67 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Data.DbContextType.ToString()));
            
            #line default
            #line hidden
            this.Write("<");
            
            #line 67 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.FullName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 67 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.DbSetName));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 68 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("\r\n\tpublic ");
            
            #line 72 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dbContextDesc.Name));
            
            #line default
            #line hidden
            this.Write("(DbContextOptions<");
            
            #line 72 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dbContextDesc.Name));
            
            #line default
            #line hidden
            this.Write("> options, Microsoft.Extensions.Logging.ILogger<");
            
            #line 72 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dbContextDesc.Name));
            
            #line default
            #line hidden
            this.Write("> logger)\r\n\t\t: base(options, logger)\r\n\t{\r\n\t}\r\n\r\n\tpublic ");
            
            #line 77 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dbContextDesc.Name));
            
            #line default
            #line hidden
            this.Write("(Microsoft.Extensions.Logging.ILogger<");
            
            #line 77 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dbContextDesc.Name));
            
            #line default
            #line hidden
            this.Write(@"> logger)
		: base(logger)
	{
	}

	protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
	{
		if (!optionsBuilder.IsConfigured)
		{
			if (ConnectionProvider == null)
				Legion.Throw.InitializationException(ConnectionProvider);

			ConnectionProvider.OnConfiguring(optionsBuilder);
		}
		else
		{
			SetIsDbContextOptionsBuilderPreconfigured();
		}

		if (DbContextSettintgs.AllowLocking == true)
			optionsBuilder.AddInterceptors(new Legion.EntityFrameworkCore.Interceptors.RowLockInterceptor_");
            
            #line 97 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(isPostgreSql ? "PostgreSql" : "SqlServer"));
            
            #line default
            #line hidden
            this.Write("());\r\n\t}\r\n\r\n\tprotected override void OnModelCreating(ModelBuilder modelBuilder)\r\n" +
                    "\t{\r\n\t\tRegisterUnaccentFunction(modelBuilder);\r\n\r\n");
            
            #line 104 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"

	foreach (var entity in dbContextDesc.Data.Entities.OrderBy(x => x.Name))
	{
		if (!entity.GenerateModel)
			continue;

		//TODO urob ine mapovanie ak entityDesc.DbContextType == DbQuery !!!!!!!!!!!!!!!!!!!!!!!!!!!!!

		var entityDesc = dbContextDesc.Context.GetEntityModelDescriptor(entity, true, modelName, contextName);
		if (entityDesc == null) continue;

            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 115 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.EntityContextModelBuilderBaseName));
            
            #line default
            #line hidden
            this.Write(".Build(modelBuilder);\r\n");
            
            #line 116 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("\t}\r\n}\r\n");
            
            #line 121 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"

	StartNewFile(dbContextDesc.AbstractionTargetFolder, dbContextDesc.AbstractionFileName);

	foreach (string import in dbContextDesc.AbstractionImports)
	{

            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 127 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(import));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 128 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"

	}
	if (0 < dbContextDesc.AbstractionImports.Count)
	{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 134 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("#nullable disable\r\n\r\nnamespace ");
            
            #line 139 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dbContextDesc.AbstractionNamespace));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\npublic interface ");
            
            #line 141 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dbContextDesc.AbstractionName));
            
            #line default
            #line hidden
            this.Write(" : Legion.EntityFrameworkCore.Audit.IAuditableDbContext, Legion.EntityFrameworkCo" +
                    "re.IDbContext, IDisposable, IAsyncDisposable\r\n{\r\n");
            
            #line 143 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"

	foreach (var entity in dbContextDesc.Data.Entities.OrderBy(x => x.Name))
	{
		var entityDesc = dbContextDesc.Context.GetEntityModelDescriptor(entity, true, modelName, contextName);
		if (entityDesc == null || !entity.GenerateModel) continue;
		//if (entity.IsAuditEntry) continue;

            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 150 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Data.DbContextType.ToString()));
            
            #line default
            #line hidden
            this.Write("<");
            
            #line 150 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.FullName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 150 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.DbSetName));
            
            #line default
            #line hidden
            this.Write(" { get; }\r\n");
            
            #line 151 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 155 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"

	Process();

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 158 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextGenerator.tt"

string MultiLineFluentApi(params string[] lines)
{
	StringBuilder sb = new StringBuilder();
	if (lines != null && 0 < lines.Length)
	{
		if (lines.Length == 1)
		{
			sb.Append(lines[0].Trim());
		}
		else
		{
			foreach (var line in lines)
			{
				sb.AppendLine();
				sb.Append(line);
			}     
		}
	}
	sb.Append(";");
	return sb.ToString();
}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
