// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Legion.Generators.AppGen.AppGenGenerators.Model
{
    using Legion.Extensions;
    using Legion.Generators.AppGen.Model;
    using Legion.Generators.AppGen.Descriptors;
    using Legion.Generators.AppGen.Descriptors.MetaDescriptors;
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class EntityModelEnumerationGenerator : Generator.GeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 12 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"

	SetGenerationEnvironment(this.GenerationEnvironment);
	
	EntityModelEnumerationDescriptor entityDesc = GetParam<EntityModelEnumerationDescriptor>("EntityModelEnumerationDescriptor");
	string modelName = GetParam<string>("modelName");
	string contextName = GetParam<string>("contextName");

	StartNewFile(entityDesc.TargetFolder(modelName, contextName), entityDesc.FileName);
	
	foreach (string import in entityDesc.Imports)
	{

            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 24 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(import));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 25 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"

	}
	if (0 < entityDesc.Imports.Count)
	{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 31 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 34 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Namespace(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\npublic partial class ");
            
            #line 36 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Name));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 36 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.GetBaseEntityName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(", Legion.Model.IEntity\r\n{\r\n");
            
            #line 38 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"

		if (entityDesc.Data.MainColumn.ClrType != typeof(string))
		{

            
            #line default
            #line hidden
            this.Write("#pragma warning disable IDE1006 // Naming Styles\r\n");
            
            #line 43 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"

		}

		int idx = 0;
		foreach (var enumRow in entityDesc.EnumData)
		{
			idx++;
			if (1 < idx)
			{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 54 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"

			}

            
            #line default
            #line hidden
            this.Write("\t/// <summary>\r\n\t/// ");
            
            #line 58 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumRow.Values[0].Replace("new Guid(\"", "").Replace("\")", "")));
            
            #line default
            #line hidden
            this.Write("\r\n\t/// </summary>\r\n\tpublic static ");
            
            #line 60 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Data.FirstPrimaryKey.CSharpType));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 60 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumRow.BasePropertyCSharpName));
            
            #line default
            #line hidden
            this.Write(" { get; }\r\n");
            
            #line 61 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"

		}

		if (entityDesc.Data.MainColumn.ClrType != typeof(string))
		{

            
            #line default
            #line hidden
            this.Write("#pragma warning restore IDE1006 // Naming Styles\r\n");
            
            #line 68 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"

		}

            
            #line default
            #line hidden
            this.Write("\r\n\tstatic ");
            
            #line 72 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Name));
            
            #line default
            #line hidden
            this.Write("()\r\n\t{\r\n");
            
            #line 74 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"

	foreach (var enumRow in entityDesc.EnumData)
	{

            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 78 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumRow.BasePropertyCSharpName));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 78 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumRow.Values[0]));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 79 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("\r\n\t\tDefaultDBValidator = SetDBValidatorRules(new Legion.Validation.ValidatorBuild" +
                    "er<");
            
            #line 83 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Name));
            
            #line default
            #line hidden
            this.Write(">()).Build();\r\n\t}\r\n\r\n\tpublic static IEnumerable<");
            
            #line 86 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Data.FirstPrimaryKey.CSharpType));
            
            #line default
            #line hidden
            this.Write("> AsEnumerable()\r\n\t{\r\n");
            
            #line 88 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"

		if (entityDesc.EnumData.Count == 0)
		{

            
            #line default
            #line hidden
            this.Write("\t\tyield return null;\r\n");
            
            #line 93 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"

		}
		else
		{
			foreach (var enumRow in entityDesc.EnumData)
			{

            
            #line default
            #line hidden
            this.Write("\t\tyield return ");
            
            #line 100 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumRow.BasePropertyCSharpName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 101 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"

			}
		}

            
            #line default
            #line hidden
            this.Write("\t}\r\n");
            
            #line 106 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"

	if (entityDesc.ConvertEntity == ConvertEntity.ToEnumAndEnumerationClass)
	{

            
            #line default
            #line hidden
            this.Write("\r\n\tpublic ");
            
            #line 111 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.EnumName));
            
            #line default
            #line hidden
            this.Write(" ToEnum()\r\n\t{\r\n");
            
            #line 113 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"

	foreach (var enumRow in entityDesc.EnumData)
	{

            
            #line default
            #line hidden
            this.Write("\t\tif (");
            
            #line 117 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Data.FirstPrimaryKey));
            
            #line default
            #line hidden
            this.Write(" == ");
            
            #line 117 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumRow.BasePropertyCSharpName));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\treturn ");
            
            #line 118 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.EnumName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 118 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumRow.BasePropertyCSharpName));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n");
            
            #line 120 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("\t\tLegion.Throw.NotSupportedException($\"Invalid {nameof(");
            
            #line 123 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Data.FirstPrimaryKey));
            
            #line default
            #line hidden
            this.Write(")} value {");
            
            #line 123 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Data.FirstPrimaryKey));
            
            #line default
            #line hidden
            this.Write("}\");\r\n\r\n\t\treturn 0;\r\n\t}\r\n\r\n\tpublic static implicit operator ");
            
            #line 128 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.EnumName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 128 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Name));
            
            #line default
            #line hidden
            this.Write(" status)\r\n\t\t=> status?.ToEnum() ?? 0;\r\n\r\n\tpublic static implicit operator ");
            
            #line 131 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Name));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 131 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.EnumName));
            
            #line default
            #line hidden
            this.Write(" @enum)\r\n\t\t=> @enum switch\r\n\t\t{\r\n");
            
            #line 134 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"

	foreach (var enumRow in entityDesc.EnumData)
	{

            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 138 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.EnumName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 138 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumRow.BasePropertyCSharpName));
            
            #line default
            #line hidden
            this.Write(" => ");
            
            #line 138 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumRow.BasePropertyCSharpName_NewObject));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 139 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("\t\t\t_ => throw new NotSupportedException($\"Invalid {nameof(");
            
            #line 142 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.EnumName));
            
            #line default
            #line hidden
            this.Write(")} value {@enum}\"),\r\n\t\t};\r\n");
            
            #line 144 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 148 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityModelEnumerationGenerator.tt"

	Process();

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
