// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Legion.Generators.AppGen.AppGenGenerators.Model
{
    using Legion.Extensions;
    using Legion.Generators.AppGen.Model;
    using Legion.Generators.AppGen.Descriptors;
    using Legion.Generators.AppGen.Descriptors.MetaDescriptors;
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class EntityContextModelBuilderGenerator : Generator.GeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 12 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"

	SetGenerationEnvironment(this.GenerationEnvironment);
	
	EntityContextDescriptor dbContextDesc = GetParam<EntityContextDescriptor>("EntityContextDescriptor");
	string modelName = GetParam<string>("modelName");
	string contextName = GetParam<string>("contextName");

	foreach (var entity in dbContextDesc.Data.Entities.OrderBy(x => x.Name))
	{
		if (!entity.GenerateModel)
			continue;

		var entityDesc = dbContextDesc.Context.GetEntityModelDescriptor(entity, true, modelName, contextName);
		if (entityDesc == null) continue;

		StartNewFile(entityDesc.EntityContextModelBuilderTargetFolder, entityDesc.EntityContextModelBuilderFileName);

		foreach (string import in entityDesc.EntityContextModelBuilderImports)
		{

            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 32 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(import));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 33 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"

		}

		if (0 < entityDesc.EntityContextModelBuilderImports.Count)
		{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 40 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"

		}

            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 43 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.EntityContextModelBuilderNamespace));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\npublic class ");
            
            #line 45 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.EntityContextModelBuilderName));
            
            #line default
            #line hidden
            this.Write(" : IEntityTypeConfiguration<");
            
            #line 45 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(">\r\n{\r\n\tpublic const string PrimaryKeyFormatter = \"");
            
            #line 47 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.GetKeyPropertiesAsJsonFormatter(entity.PrimaryKey)));
            
            #line default
            #line hidden
            this.Write("\";\r\n\r\n\tpublic void Configure(EntityTypeBuilder<");
            
            #line 49 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write("> entityBuilder)\r\n\t\t=> ConfigureEntity(entityBuilder);\r\n\r\n\tpublic static void Con" +
                    "figureEntity(EntityTypeBuilder<");
            
            #line 52 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write("> entityBuilder)\r\n\t{\r\n");
            
            #line 54 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"

		//PRIMARY KEY

            
            #line default
            #line hidden
            this.Write("\t\tentityBuilder.HasKey(e => ");
            
            #line 57 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.GetKeyPropertiesAsLambda(entity.PrimaryKey, "e")));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 58 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"

		//TABLE

            
            #line default
            #line hidden
            this.Write("\r\n\t\tentityBuilder.ToTable(");
            
            #line 62 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Text.StringHelper.DelimitString(entity.TableName)));
            
            #line default
            #line hidden
            
            #line 62 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.IsExplicitSchemaName ? (", " + Text.StringHelper.DelimitString(entity.Schema)) : ""));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 63 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"

		//INDEX
		foreach (var index in entity.Indexes)
		{
			string lineDelimiter = (index.IsUnique || !string.IsNullOrWhiteSpace(index.Filter)) ? "" : ";";

            
            #line default
            #line hidden
            this.Write("\r\n\t\tentityBuilder.HasIndex(e => ");
            
            #line 70 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.GetIndexPropertiesAsLambda(index, "e")));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 70 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Text.StringHelper.DelimitString(index.Name)));
            
            #line default
            #line hidden
            this.Write(")");
            
            #line 70 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lineDelimiter));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 71 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"

			if (index.IsUnique)
			{
				lineDelimiter = !string.IsNullOrWhiteSpace(index.Filter) ? "" : ";";

            
            #line default
            #line hidden
            this.Write("\t\t\t\t.IsUnique()");
            
            #line 76 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(lineDelimiter));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 77 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"

			}
			if (!string.IsNullOrWhiteSpace(index.Filter))
			{

            
            #line default
            #line hidden
            this.Write("\t\t\t\t.HasFilter(");
            
            #line 82 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Text.StringHelper.DelimitString(index.Filter)));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 83 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"

			}
		}

		//Properties
		foreach (var property in entity.Properties.Where(x => !x.IsIgnored))
		{
			List<string> lines = new List<string>();
			if (property.IsRequiredEfMapping)
			{
				lines.Add("			.IsRequired()");
			}
			if (property.IsExplicitName)
			{
				lines.Add("			.HasColumnName(" + Text.StringHelper.DelimitString(property.ColumnName) + ")");
			}
			if (property.HasJsonConversion)
			{
				lines.Add("			.HasConversion(");
				lines.Add("				v => Legion.Serializer.JsonSerializerHelper.Serialize(v, true),");
				lines.Add($"				v => Legion.Serializer.JsonSerializerHelper.Deserialize<{property.CSharpType}>(v, true),");
				lines.Add($"				new Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer<{property.CSharpType}>(");
				lines.Add($"					(c1, c2) => (c1 == null && c2 == null) || (c1 != null && c2 != null && c1.SequenceEqual(c2)),");
				lines.Add($"					c => c == null ? 0 : c.Aggregate(0, (a, v) => HashCode.Combine(a, v.GetHashCode())),");
				lines.Add($"					c => c == null ? null! : c.ToList())");
				lines.Add("			)");
			}
			if (!string.IsNullOrWhiteSpace(property.ConfiguredColumnType))
			{
				lines.Add("			.HasColumnType(" + Text.StringHelper.DelimitString(property.ConfiguredColumnType) + ")");
			}
			if (property.ClrType == typeof(string) && property.MaxLength.HasValue)
			{
				lines.Add("			.HasMaxLength(" + Text.StringHelper.GenerateLiteral(property.MaxLength.Value) + ")");
			}
			if (false /*TODO*/ && property.Precision.HasValue)
			{
				lines.Add("			.HasMaxLength(" + Text.StringHelper.GenerateLiteral(property.Precision.Value) + ")");
			}
			if (property.IsUnicode.HasValue)
			{
				lines.Add("			.IsUnicode(" + (property.IsUnicode == false ? Text.StringHelper.GenerateLiteral(false) : "") + ")");
			}
			if (property.DefaultValue != null)
			{
				lines.Add("			.HasDefaultValue(" + Text.StringHelper.GenerateLiteral((dynamic)property.DefaultValue) + ")");
			}
			if (!string.IsNullOrWhiteSpace(property.DefaultValueSql))
			{
				lines.Add("		.HasDefaultValueSql(" + Text.StringHelper.DelimitString(property.DefaultValueSql) + ")");
			}
			if (!string.IsNullOrWhiteSpace(property.ComputedColumnSql))
			{
				lines.Add("				.HasComputedColumnSql(" + Text.StringHelper.DelimitString(property.ComputedColumnSql) + ")");
			}
			if (!string.IsNullOrWhiteSpace(property.ValueGeneratedMetohdName))
			{
				lines.Add("		." + property.ValueGeneratedMetohdName + "()");
			}
			if (property.IsConcurrencyToken)
			{
				lines.Add("				.IsConcurrencyToken()");
			}

			string propertyFluent = MultiLineFluentApi(lines.ToArray());
			if (propertyFluent != ";")
			{

            
            #line default
            #line hidden
            this.Write("\r\n\t\tentityBuilder.Property(e => e.");
            
            #line 152 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(")");
            
            #line 152 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyFluent));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 153 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"

			}
		}

		//Relationship
		foreach (var foreignKey in entity.ForeignKeys)
		{
			if (foreignKey.DependentToPrincipal.Ignore
				|| !foreignKey.DependentToPrincipal.TargetType.ModelContextNames.ContainsKey(modelName))
				continue;

			bool isOneToOne = !foreignKey.DependentToPrincipal.BackNavigation.IsCollection;
			string relation = isOneToOne ? "WithOne" : "WithMany";
			if (!foreignKey.PrincipalEntity.GenerateModel)
				continue;

			var navigationExpression = foreignKey.PrincipalToDependent.Ignore || !foreignKey.PrincipalToDependent.TargetType.ModelContextNames.ContainsKey(modelName)
				? ""
				: "p => p." + foreignKey.PrincipalToDependent.Name;

            
            #line default
            #line hidden
            this.Write("\r\n\t\tentityBuilder.HasOne(d => d.");
            
            #line 174 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(foreignKey.DependentToPrincipal.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t.");
            
            #line 175 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 175 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigationExpression));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 176 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"

			if (!foreignKey.PrincipalKeyIsPrimaryKey)
			{

            
            #line default
            #line hidden
            this.Write("\t\t\t.HasPrincipalKey");
            
            #line 180 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(foreignKey.IsUnique ? ("<" + entityDesc.Context.GetEntityModelDescriptor(foreignKey.PrincipalEntity, false, modelName, contextName).BaseName(modelName, contextName) + ">") : ""));
            
            #line default
            #line hidden
            this.Write("(p => ");
            
            #line 180 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.GetForeignKeyPropertiesAsLambda(foreignKey, "p")));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 181 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"

			}

            
            #line default
            #line hidden
            this.Write("\t\t\t.HasForeignKey");
            
            #line 184 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(isOneToOne ? ("<" + entityDesc.Context.GetEntityModelDescriptor(foreignKey.DeclaringEntity, false, modelName, contextName).BaseName(modelName, contextName) + ">") : ""));
            
            #line default
            #line hidden
            this.Write("(d => ");
            
            #line 184 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.GetForeignKeyPrincipalKeyPropertiesAsLambda(foreignKey, "d")));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 185 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"

			if (foreignKey.DeleteBehavior != foreignKey.DefaultDeleteBehavior)
			{

            
            #line default
            #line hidden
            this.Write("\t\t\t.OnDelete(");
            
            #line 189 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Text.StringHelper.GenerateLiteral(foreignKey.DeleteBehavior)));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 190 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"

			}

            
            #line default
            #line hidden
            this.Write("\t\t\t.HasConstraintName(");
            
            #line 193 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Text.StringHelper.DelimitString(foreignKey.Name)));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 194 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"

		}

		var ignoredDependentToPrincipalForeignKeys =
			entity.BackNavigations
				.SelectMany(x => x.TargetType.ForeignKeys)
				.Where(fk => fk.DependentToPrincipal.Ignore || !fk.DependentToPrincipal.TargetType.ModelContextNames.ContainsKey(modelName))
				.ToList();

		//ignoredDependentToPrincipal Relationships
		foreach (var foreignKey in ignoredDependentToPrincipalForeignKeys)
		{
			bool isOneToOne = !foreignKey.PrincipalToDependent.IsCollection;
			if (!foreignKey.PrincipalEntity.GenerateModel)
				continue;

			if ((foreignKey.DependentToPrincipal.Ignore
					|| !foreignKey.DependentToPrincipal.TargetType.ModelContextNames.ContainsKey(modelName))
				&& (foreignKey.PrincipalToDependent.Ignore
					|| !foreignKey.PrincipalToDependent.TargetType.ModelContextNames.ContainsKey(modelName)))
				continue;
			
				string relation = isOneToOne ? "HasOne" : "HasMany";

            
            #line default
            #line hidden
            this.Write("\r\n\t\tentityBuilder.");
            
            #line 219 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(relation));
            
            #line default
            #line hidden
            this.Write("(d => d.");
            
            #line 219 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(foreignKey.PrincipalToDependent.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t.WithOne()\r\n");
            
            #line 221 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"

			if (!foreignKey.PrincipalKeyIsPrimaryKey)
			{

            
            #line default
            #line hidden
            this.Write("\t\t\t.HasPrincipalKey");
            
            #line 225 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(foreignKey.IsUnique ? ("<" + entityDesc.Context.GetEntityModelDescriptor(foreignKey.PrincipalEntity, false, modelName, contextName).BaseName(modelName, contextName) + ">") : ""));
            
            #line default
            #line hidden
            this.Write("(p => ");
            
            #line 225 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.GetForeignKeyPropertiesAsLambda(foreignKey, "p")));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 226 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"

			}

            
            #line default
            #line hidden
            this.Write("\t\t\t.HasForeignKey");
            
            #line 229 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(isOneToOne ? ("<" + entityDesc.Context.GetEntityModelDescriptor(foreignKey.DeclaringEntity, false, modelName, contextName).BaseName(modelName, contextName) + ">") : ""));
            
            #line default
            #line hidden
            this.Write("(d => ");
            
            #line 229 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.GetForeignKeyPrincipalKeyPropertiesAsLambda(foreignKey, "d")));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 230 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"

			if (foreignKey.DeleteBehavior != foreignKey.DefaultDeleteBehavior)
			{

            
            #line default
            #line hidden
            this.Write("\t\t\t.OnDelete(");
            
            #line 234 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Text.StringHelper.GenerateLiteral(foreignKey.DeleteBehavior)));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 235 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"

			}

            
            #line default
            #line hidden
            this.Write("\t\t\t.HasConstraintName(");
            
            #line 238 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Text.StringHelper.DelimitString(foreignKey.Name)));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 239 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"

		}

            
            #line default
            #line hidden
            this.Write("\t}\r\n\r\n\tpublic static ModelBuilder Build(ModelBuilder modelBuilder)\r\n\t{\r\n\t\tmodelBu" +
                    "ilder.Entity<");
            
            #line 246 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(">(ConfigureEntity);\r\n");
            
            #line 247 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"

	//Sequences
	//TODO:
	dbContextDesc.Data.Sequences = new List<SequenceBase>();

	foreach (var sequence in dbContextDesc.Data.Sequences)
	{
		List<string> lines = new List<string>();
		if (sequence.StartValue != sequence.StartValue)
		{
				lines.Add("		.StartsAt(" + sequence.StartValue + ")");
		}
		if (sequence.IncrementBy != sequence.IncrementBy)
		{
				lines.Add("		.IncrementsBy(" + sequence.IncrementBy + ")");
		}
		if (sequence.MinValue != sequence.MinValue)
		{
				lines.Add("		.HasMin(" + sequence.MinValue + ")");
		}
		if (sequence.MaxValue != sequence.MaxValue)
		{
				lines.Add("		.HasMax(" + sequence.MaxValue + ")");
		}
		if (sequence.IsCyclic != sequence.IsCyclic)
		{
				lines.Add("		.IsCyclic()");
		}

            
            #line default
            #line hidden
            this.Write("\r\n\t\tmodelBuilder.HasSequence");
            
            #line 277 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sequence.ClrType != sequence.ClrType ? ("<" + Helpers.TypeHelper.TypeToCSharpSourceCode(sequence.ClrType) + ">") : ""));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 277 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Text.StringHelper.DelimitString(sequence.Name)));
            
            #line default
            #line hidden
            
            #line 277 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(sequence.IsExplicitSchema ? (", " + Text.StringHelper.DelimitString(sequence.Schema)) : ""));
            
            #line default
            #line hidden
            this.Write(")");
            
            #line 277 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(MultiLineFluentApi(lines.ToArray())));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 278 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("\r\n\t\treturn modelBuilder;\r\n\t}\r\n}\r\n");
            
            #line 285 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"

	}
	Process();

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 289 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\EntityContextModelBuilderGenerator.tt"

string MultiLineFluentApi(params string[] lines)
{
	StringBuilder sb = new StringBuilder();
	if (lines != null && 0 < lines.Length)
	{
		if (lines.Length == 1)
		{
			sb.Append(lines[0].Trim());
		}
		else
		{
			foreach (var line in lines)
			{
				sb.AppendLine();
				sb.Append(line);
			}
		}
	}
	sb.Append(";");
	return sb.ToString();
}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
