// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Legion.Generators.AppGen.AppGenGenerators.Model
{
    using Legion.Extensions;
    using Legion.Generators.AppGen.Model;
    using Legion.Generators.AppGen.Descriptors;
    using Legion.Generators.AppGen.Descriptors.MetaDescriptors;
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryModelGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class QueryModelGenerator : Generator.GeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 12 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryModelGenerator.tt"

	SetGenerationEnvironment(this.GenerationEnvironment);
	
	QueryModelDescriptor entityDesc = GetParam<QueryModelDescriptor>("QueryModelDescriptor");
	string modelName = GetParam<string>("modelName");
	string contextName = GetParam<string>("contextName");

	StartNewFile(entityDesc.TargetFolder(modelName, contextName), entityDesc.FileName);
	
	string @sealed = entityDesc.Data.IsSealed ? " sealed" : "";
	string customInterfaces = string.IsNullOrWhiteSpace(entityDesc.Data.CustomInterfaces) ? "" : ", " + entityDesc.Data.CustomInterfaces;

	foreach (string import in entityDesc.Imports)
	{

            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 27 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryModelGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(import));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 28 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryModelGenerator.tt"

	}
	if (0 < entityDesc.Imports.Count)
	{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 34 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryModelGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 37 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryModelGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Namespace(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\npublic");
            
            #line 39 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryModelGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(@sealed));
            
            #line default
            #line hidden
            this.Write(" partial class ");
            
            #line 39 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryModelGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Name));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 39 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryModelGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.GetBaseQueryEntityName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(", Legion.Model.IQueryEntity");
            
            #line 39 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryModelGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(customInterfaces));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 41 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryModelGenerator.tt"

	foreach (var property in entityDesc.Properties)
	{
		var isNullableString = property.ClrType == typeof(string) && property.Data.IsNullable;
		var nullableString = isNullableString
			? "?"
			: "";

		var isNullableByteArray = property.ClrType == typeof(byte[]) && property.Data.IsNullable;
		var nullableByteArray = isNullableByteArray
			? "?"
			: "";

		var isNullableList = property.IsCollection();
		var nullableList = (isNullableList && !isNullableByteArray)
			? "?"
			: "";

		var dbDataType = property.Data.GetDatabaseDataType(true);

            
            #line default
            #line hidden
            this.Write("\t/// <summary>\r\n\t/// Database DataType: ");
            
            #line 62 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryModelGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dbDataType));
            
            #line default
            #line hidden
            this.Write("\r\n\t/// </summary>\r\n\tpublic ");
            
            #line 64 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryModelGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helpers.TypeHelper.TypeToCSharpSourceCode(property.ClrType)));
            
            #line default
            #line hidden
            
            #line 64 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryModelGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(nullableString));
            
            #line default
            #line hidden
            
            #line 64 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryModelGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(nullableByteArray));
            
            #line default
            #line hidden
            
            #line 64 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryModelGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(nullableList));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 64 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryModelGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" { get; private set; }\r\n\r\n");
            
            #line 66 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryModelGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("\r\n\tprivate ");
            
            #line 70 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryModelGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Name));
            
            #line default
            #line hidden
            this.Write("()\r\n\t{\r\n\t}\r\n\r\n\tpublic Dictionary<string, object?> ToDictionary()\r\n\t\t=> new()\r\n\t\t{" +
                    "\r\n");
            
            #line 77 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryModelGenerator.tt"

	foreach (var property in entityDesc.Properties/*.Where(x => !x.Data.IsIgnored)*/)
	{

            
            #line default
            #line hidden
            this.Write("\t\t\t{ nameof(");
            
            #line 81 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryModelGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("), ");
            
            #line 81 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryModelGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" },\r\n");
            
            #line 82 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryModelGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("\t\t};\r\n\r\n\tpublic override string? ToString()\r\n\t{\r\n\t\treturn ");
            
            #line 89 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryModelGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.PropertyToString(entityDesc.Data.MainColumn)));
            
            #line default
            #line hidden
            this.Write(";\r\n\t}\r\n}\r\n");
            
            #line 92 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryModelGenerator.tt"

	Process();

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
