// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Legion.Generators.AppGen.AppGenGenerators.Model
{
    using Legion.Extensions;
    using Legion.Generators.AppGen.Model;
    using Legion.Generators.AppGen.Descriptors;
    using Legion.Generators.AppGen.Descriptors.MetaDescriptors;
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryRepositoryGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class QueryRepositoryGenerator : Generator.GeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 12 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryRepositoryGenerator.tt"

	SetGenerationEnvironment(this.GenerationEnvironment);
	
	QueryRepositoryDescriptor repoDesc = GetParam<QueryRepositoryDescriptor>("QueryRepositoryDescriptor");
	string modelName = GetParam<string>("modelName");
	string contextName = GetParam<string>("contextName");

	StartNewFile(repoDesc.InterfaceTargetFolder, repoDesc.InterfaceFileName);
	
	foreach (string import in repoDesc.InterfaceImports)
	{

            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 24 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryRepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(import));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 25 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryRepositoryGenerator.tt"

	}
	if (0 < repoDesc.InterfaceImports.Count)
	{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 31 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryRepositoryGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 34 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryRepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(repoDesc.InterfaceNamespace));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\npublic partial interface ");
            
            #line 36 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryRepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(repoDesc.InterfaceName));
            
            #line default
            #line hidden
            this.Write(" : Legion.Model.Repositories.IQueryRepositoryBase\r\n{\r\n}\r\n\r\npublic interface ");
            
            #line 40 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryRepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(repoDesc.InterfaceName));
            
            #line default
            #line hidden
            this.Write("<T> : Legion.Model.Repositories.IQueryRepositoryBase<T>, ");
            
            #line 40 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryRepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(repoDesc.InterfaceName));
            
            #line default
            #line hidden
            this.Write(", Legion.Model.Repositories.IQueryRepositoryBase\r\n{\r\n}\r\n");
            
            #line 43 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryRepositoryGenerator.tt"

	StartNewFile(repoDesc.BaseRepoTargetFolder, repoDesc.BaseRepoFileName);

	var dbConnection = AppGen.Model.Config.CodeGeneratorConfig.Instance.SelectedDatabaseConnection.Provider == Database.Metamodel.DatabaseProviderType.PostgreSQL ? "NpgsqlConnection" : "SqlConnection";

	foreach (string import in repoDesc.BaseRepoImports)
	{

            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 51 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryRepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(import));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 52 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryRepositoryGenerator.tt"

	}
	if (0 < repoDesc.BaseRepoImports.Count)
	{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 58 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryRepositoryGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 61 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryRepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(repoDesc.BaseRepoNamespace));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\npublic abstract partial class ");
            
            #line 63 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryRepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(repoDesc.BaseRepoName));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 63 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryRepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(repoDesc.InterfaceNamespace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 63 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryRepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(repoDesc.InterfaceName));
            
            #line default
            #line hidden
            this.Write(", Legion.Model.Repositories.IQueryRepositoryBase\r\n{\r\n\tpublic IEFConnectionProvide" +
                    "r ConnectionProvider { get; }\r\n\r\n\tpublic ");
            
            #line 67 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryRepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(repoDesc.BaseRepoName));
            
            #line default
            #line hidden
            this.Write("(\r\n\t\tIEFConnectionProvider connectionProvider)\r\n\t{\r\n\t\tThrow.IfArgumentNull(connec" +
                    "tionProvider);\r\n\r\n\t\tConnectionProvider = connectionProvider;\r\n\t}\r\n\r\n\tprotected ");
            
            #line 75 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryRepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(repoDesc.DbContextFullName));
            
            #line default
            #line hidden
            this.Write(" GetContext(IScopeContext scopeContext)\r\n\t\t=> ConnectionProvider.GetOrCreateDbCon" +
                    "text<");
            
            #line 76 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryRepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(repoDesc.DbContextFullName));
            
            #line default
            #line hidden
            this.Write(">(scopeContext);\r\n\r\n\tprotected ");
            
            #line 78 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryRepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dbConnection));
            
            #line default
            #line hidden
            this.Write(" GetDbConnection()\r\n\t\t=> (");
            
            #line 79 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryRepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dbConnection));
            
            #line default
            #line hidden
            this.Write(")ConnectionProvider.GetDbConnection()!;\r\n\r\n\tprotected ");
            
            #line 81 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryRepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dbConnection));
            
            #line default
            #line hidden
            this.Write(" GetOrCreateNewDbConnection(out bool isNewConnection)\r\n\t\t=> (");
            
            #line 82 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryRepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dbConnection));
            
            #line default
            #line hidden
            this.Write(")ConnectionProvider.GetOrCreateNewDbConnection(out isNewConnection)!;\r\n\r\n\tprotect" +
                    "ed ");
            
            #line 84 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryRepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dbConnection));
            
            #line default
            #line hidden
            this.Write(" CreateNewDbConnection()\r\n\t\t=> (");
            
            #line 85 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryRepositoryGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dbConnection));
            
            #line default
            #line hidden
            this.Write(")ConnectionProvider.CreateNewDbConnection()!;\r\n}\r\n");
            
            #line 87 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryRepositoryGenerator.tt"

	Process();

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
