// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Legion.Generators.AppGen.AppGenGenerators.Model
{
    using Legion.Extensions;
    using Legion.Generators.AppGen.Model;
    using Legion.Generators.AppGen.Descriptors;
    using Legion.Generators.AppGen.Descriptors.MetaDescriptors;
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class QueryTableInfoGenerator : Generator.GeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 12 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"

	SetGenerationEnvironment(this.GenerationEnvironment);
	
	QueryTableInfoDescriptor tabInfoDesc = GetParam<QueryTableInfoDescriptor>("QueryTableInfoDescriptor");
	string modelName = GetParam<string>("modelName");
	string contextName = GetParam<string>("contextName");

	StartNewFile(tabInfoDesc.InterfaceTargetFolder, tabInfoDesc.InterfaceFileName);
	
	foreach (string import in tabInfoDesc.InterfaceImports)
	{

            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 24 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(import));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 25 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"

	}
	if (0 < tabInfoDesc.InterfaceImports.Count)
	{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 31 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 34 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabInfoDesc.InterfaceNamespace));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\npublic interface ");
            
            #line 36 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabInfoDesc.InterfaceName));
            
            #line default
            #line hidden
            this.Write(" : Legion.Database.ITableInfoProvider\r\n{\r\n}\r\n");
            
            #line 39 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"

	StartNewFile(tabInfoDesc.TableInfoTargetFolder, tabInfoDesc.FileName);

	var dbConnection = AppGen.Model.Config.CodeGeneratorConfig.Instance.SelectedDatabaseConnection.Provider == Database.Metamodel.DatabaseProviderType.PostgreSQL ? "NpgsqlConnection" : "SqlConnection";

	foreach (string import in tabInfoDesc.Imports)
	{

            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 47 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(import));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 48 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"

	}
	if (0 < tabInfoDesc.Imports.Count)
	{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 54 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 57 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabInfoDesc.TableInfoNamespace));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\npublic class ");
            
            #line 59 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabInfoDesc.Name));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 59 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabInfoDesc.InterfaceNamespace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 59 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tabInfoDesc.InterfaceName));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 61 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"

	foreach (var entity in tabInfoDesc.Model.QueryEntities)
	{
		var entityDesc = tabInfoDesc.Context.GetQueryModelDescriptor(entity, modelName, contextName);
		if (entityDesc == null) continue;

            
            #line default
            #line hidden
            this.Write("\tprivate readonly static Lazy<Legion.Database.Metamodel.Info.TableInfo> _");
            
            #line 67 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("TableInfo = new(() =>\r\n\t\tnew Legion.Database.Metamodel.Info.TableInfo(\r\n\t\t\t\t\"");
            
            #line 69 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Schema));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 69 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AppGen.Model.Config.CodeGeneratorConfig.Instance.SelectedDatabaseConnection.Provider == Database.Metamodel.DatabaseProviderType.PostgreSQL ? $"\\\"{entity.TableName}\\\"" : $"[{entity.TableName}]"));
            
            #line default
            #line hidden
            this.Write("\",\r\n\t\t\t\t[\r\n");
            
            #line 71 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"

		foreach (var property in entity.Properties/*.Where(x => !x.IsIgnored)*/)
		{

            
            #line default
            #line hidden
            this.Write("\t\t\t\t\tnew(nameof(");
            
            #line 75 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.FullName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 75 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("), typeof(");
            
            #line 75 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Helpers.TypeHelper.TypeToCSharpSourceCode(property.ClrType)));
            
            #line default
            #line hidden
            this.Write("), \"");
            
            #line 75 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(AppGen.Model.Config.CodeGeneratorConfig.Instance.SelectedDatabaseConnection.Provider == Database.Metamodel.DatabaseProviderType.PostgreSQL ? $"\\\"{property.ColumnName}\\\"" : $"[{property.ColumnName}]"));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 75 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.GetDatabaseDataType(false)));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 75 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.IsNullable.ToString().ToLower()));
            
            #line default
            #line hidden
            this.Write("),\r\n");
            
            #line 76 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"

		}

            
            #line default
            #line hidden
            this.Write("\t\t\t\t]));\r\n\r\n\tpublic static Legion.Database.Metamodel.Info.TableInfo Get");
            
            #line 81 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("TableInfo()\r\n\t\t=> _");
            
            #line 82 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("TableInfo.Value;\r\n\r\n");
            
            #line 84 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("\tprivate readonly static Lazy<Dictionary<Type, Legion.Database.Metamodel.Info.Tab" +
                    "leInfo>> _tableInfoDictionary =\r\n\t\tnew(() => new Dictionary<Type, Legion.Databas" +
                    "e.Metamodel.Info.TableInfo>\r\n\t\t{\r\n");
            
            #line 90 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"

	foreach (var entity in tabInfoDesc.Model.QueryEntities)
	{
		var entityDesc = tabInfoDesc.Context.GetQueryModelDescriptor(entity, modelName, contextName);
		if (entityDesc == null) continue;

            
            #line default
            #line hidden
            this.Write("\t\t\t{ typeof(");
            
            #line 96 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entityDesc.Namespace(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 96 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("), Get");
            
            #line 96 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Name));
            
            #line default
            #line hidden
            this.Write("TableInfo() },\r\n");
            
            #line 97 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write(@"		});

	public IReadOnlyDictionary<Type, Legion.Database.Metamodel.Info.TableInfo> TableInfoDictionary => _tableInfoDictionary.Value;

	public Legion.Database.Metamodel.Info.TableInfo GetTableInfo<T>()
		=> GetTableInfo(typeof(T));

	public Legion.Database.Metamodel.Info.TableInfo GetTableInfo(Type type)
	{
		if (TableInfoDictionary.TryGetValue(type, out var tableInfo))
			return tableInfo;

		Legion.Throw.InvalidOperationException($""Invalid entity type = {type.ToFriendlyFullName()}"");
		return null;
	}
}
");
            
            #line 116 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryTableInfoGenerator.tt"

	Process();

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
