// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Legion.Generators.AppGen.AppGenGenerators.Model
{
    using Legion.Extensions;
    using Legion.Generators.AppGen.Model;
    using Legion.Generators.AppGen.Descriptors;
    using Legion.Generators.AppGen.Descriptors.MetaDescriptors;
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class QueryContextGenerator : Generator.GeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 12 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextGenerator.tt"

	SetGenerationEnvironment(this.GenerationEnvironment);

	QueryContextDescriptor dbContextDesc = GetParam<QueryContextDescriptor>("QueryContextDescriptor");
	string modelName = GetParam<string>("modelName");
	string contextName = GetParam<string>("contextName");

	StartNewFile(dbContextDesc.TargetFolder(modelName, contextName), dbContextDesc.FileName);

	foreach (string import in dbContextDesc.Imports)
	{

            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 24 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(import));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 25 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextGenerator.tt"

	}
	if (0 < dbContextDesc.Imports.Count)
	{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 31 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("#nullable disable\r\n\r\nnamespace ");
            
            #line 36 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dbContextDesc.Namespace(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\npublic partial class ");
            
            #line 38 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dbContextDesc.Name));
            
            #line default
            #line hidden
            this.Write(" : Legion.EntityFrameworkCore.DbContextBase, ");
            
            #line 38 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dbContextDesc.AbstractionBaseNamespace));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 38 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dbContextDesc.AbstractionName));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 40 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextGenerator.tt"

	foreach (var queryEntity in dbContextDesc.Data.QueryEntities.OrderBy(x => x.Name))
	{
		var queryEntityDesc = dbContextDesc.Context.GetQueryModelDescriptor(queryEntity, modelName, contextName);
		if (queryEntityDesc == null || !queryEntity.GenerateQueryModel) continue;

            
            #line default
            #line hidden
            this.Write("\tpublic virtual DbSet<");
            
            #line 46 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryEntityDesc.FullName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 46 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryEntity.DbSetName));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 47 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("\r\n\tpublic ");
            
            #line 51 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dbContextDesc.Name));
            
            #line default
            #line hidden
            this.Write("(DbContextOptions<");
            
            #line 51 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dbContextDesc.Name));
            
            #line default
            #line hidden
            this.Write("> options, Microsoft.Extensions.Logging.ILogger<");
            
            #line 51 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dbContextDesc.Name));
            
            #line default
            #line hidden
            this.Write("> logger)\r\n\t\t: base(options, logger)\r\n\t{\r\n\t}\r\n\r\n\tpublic ");
            
            #line 56 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dbContextDesc.Name));
            
            #line default
            #line hidden
            this.Write("(Microsoft.Extensions.Logging.ILogger<");
            
            #line 56 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dbContextDesc.Name));
            
            #line default
            #line hidden
            this.Write(@"> logger)
		: base(logger)
	{
	}

	protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
	{
		optionsBuilder.UseQueryTrackingBehavior(QueryTrackingBehavior.NoTracking);
		
		if (!optionsBuilder.IsConfigured)
		{
			if (ConnectionProvider == null)
				Legion.Throw.InitializationException(ConnectionProvider);

			ConnectionProvider.OnConfiguring(optionsBuilder);
		}
		else
		{
			SetIsDbContextOptionsBuilderPreconfigured();
		}
	}

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		RegisterUnaccentFunction(modelBuilder);

");
            
            #line 82 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextGenerator.tt"

	foreach (var queryEntity in dbContextDesc.Data.QueryEntities.OrderBy(x => x.Name))
	{
		if (!queryEntity.GenerateQueryModel)
			continue;

		var queryEntityDesc = dbContextDesc.Context.GetQueryModelDescriptor(queryEntity, modelName, contextName);
		if (queryEntityDesc == null) continue;

            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 91 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryEntityDesc.QueryContextModelBuilderBaseName));
            
            #line default
            #line hidden
            this.Write(".Build(modelBuilder);\r\n");
            
            #line 92 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("\t}\r\n}\r\n");
            
            #line 97 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextGenerator.tt"

	StartNewFile(dbContextDesc.AbstractionTargetFolder, dbContextDesc.AbstractionFileName);

	foreach (string import in dbContextDesc.AbstractionImports)
	{

            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 103 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(import));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 104 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextGenerator.tt"

	}
	if (0 < dbContextDesc.AbstractionImports.Count)
	{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 110 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 113 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dbContextDesc.AbstractionNamespace));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\npublic interface ");
            
            #line 115 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(dbContextDesc.AbstractionName));
            
            #line default
            #line hidden
            this.Write(" : Legion.EntityFrameworkCore.IDbContext, IDisposable, IAsyncDisposable\r\n{\r\n");
            
            #line 117 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextGenerator.tt"

	foreach (var queryEntity in dbContextDesc.Data.QueryEntities.OrderBy(x => x.Name))
	{
		var queryEntityDesc = dbContextDesc.Context.GetQueryModelDescriptor(queryEntity, modelName, contextName);
		if (queryEntityDesc == null || !queryEntity.GenerateQueryModel) continue;

            
            #line default
            #line hidden
            this.Write("\tDbSet<");
            
            #line 123 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryEntityDesc.FullName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 123 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryEntity.DbSetName));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 124 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 128 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextGenerator.tt"

	Process();

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 131 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextGenerator.tt"

string MultiLineFluentApi(params string[] lines)
{
	StringBuilder sb = new StringBuilder();
	if (lines != null && 0 < lines.Length)
	{
		if (lines.Length == 1)
		{
			sb.Append(lines[0].Trim());
		}
		else
		{
			foreach (var line in lines)
			{
				sb.AppendLine();
				sb.Append(line);
			}
		}
	}
	sb.Append(";");
	return sb.ToString();
}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
