// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Legion.Generators.AppGen.AppGenGenerators.Model
{
    using Legion.Extensions;
    using Legion.Generators.AppGen.Model;
    using Legion.Generators.AppGen.Descriptors;
    using Legion.Generators.AppGen.Descriptors.MetaDescriptors;
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextModelBuilderGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class QueryContextModelBuilderGenerator : Generator.GeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 12 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextModelBuilderGenerator.tt"

	SetGenerationEnvironment(this.GenerationEnvironment);
	
	QueryContextDescriptor dbContextDesc = GetParam<QueryContextDescriptor>("QueryContextDescriptor");
	string modelName = GetParam<string>("modelName");
	string contextName = GetParam<string>("contextName");

	foreach (var queryEntity in dbContextDesc.Data.QueryEntities.OrderBy(x => x.Name))
	{
		if (!queryEntity.GenerateQueryModel)
			continue;

		var queryEntityDesc = dbContextDesc.Context.GetQueryModelDescriptor(queryEntity, modelName, contextName);
		if (queryEntityDesc == null) continue;

		StartNewFile(queryEntityDesc.QueryContextModelBuilderTargetFolder, queryEntityDesc.QueryContextModelBuilderFileName);

		foreach (string import in queryEntityDesc.QueryContextModelBuilderImports)
		{

            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 32 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(import));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 33 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextModelBuilderGenerator.tt"

		}
	if (0 < queryEntityDesc.QueryContextModelBuilderImports.Count)
	{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 39 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextModelBuilderGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 42 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryEntityDesc.QueryContextModelBuilderNamespace));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\npublic class ");
            
            #line 44 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryEntityDesc.QueryContextModelBuilderName));
            
            #line default
            #line hidden
            this.Write(" : IEntityTypeConfiguration<");
            
            #line 44 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryEntityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(">\r\n{\r\n\tpublic void Configure(EntityTypeBuilder<");
            
            #line 46 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryEntityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write("> entityBuilder)\r\n\t\t=> ConfigureEntity(entityBuilder);\r\n\r\n\tpublic static void Con" +
                    "figureEntity(EntityTypeBuilder<");
            
            #line 49 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryEntityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write("> entityBuilder)\r\n\t{\r\n\t\tentityBuilder.ToView(");
            
            #line 51 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Text.StringHelper.DelimitString(queryEntity.TableName)));
            
            #line default
            #line hidden
            
            #line 51 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryEntity.IsExplicitSchemaName ? (", " + Text.StringHelper.DelimitString(queryEntity.Schema)) : ""));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t.HasNoKey();\r\n");
            
            #line 53 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextModelBuilderGenerator.tt"

		foreach (var property in queryEntity.Properties)
		{
			List<string> lines = new List<string>();
			if (property.IsRequiredEfMapping)
			{
				lines.Add("			.IsRequired()");
			}
			if (property.HasJsonConversion)
			{
				lines.Add("			.HasConversion(");
				lines.Add("				v => Legion.Serializer.JsonSerializerHelper.Serialize(v, true),");
				lines.Add($"				v => Legion.Serializer.JsonSerializerHelper.Deserialize<{property.CSharpType}>(v, true),");
				lines.Add($"				new Microsoft.EntityFrameworkCore.ChangeTracking.ValueComparer<{property.CSharpType}>(");
				lines.Add($"					(c1, c2) => (c1 == null && c2 == null) || (c1 != null && c2 != null && c1.SequenceEqual(c2)),");
				lines.Add($"					c => c == null ? 0 : c.Aggregate(0, (a, v) => HashCode.Combine(a, v.GetHashCode())),");
				lines.Add($"					c => c == null ? null! : c.ToList())");
				lines.Add("			)");
			}
			if (property.IsExplicitName)
			{
				lines.Add("			.HasColumnName(" + Text.StringHelper.DelimitString(property.ColumnName) + ")");
			}
			if (!string.IsNullOrWhiteSpace(property.ConfiguredColumnType))
			{
				lines.Add("			.HasColumnType(" + Text.StringHelper.DelimitString(property.ConfiguredColumnType) + ")");
			}
			if (false && property.MaxLength.HasValue)
			{
				lines.Add("			.HasMaxLength(" + Text.StringHelper.GenerateLiteral(property.MaxLength.Value) + ")");
			}
			if (property.IsUnicode.HasValue)
			{
				lines.Add("			.IsUnicode(" + (property.IsUnicode == false ? Text.StringHelper.GenerateLiteral(false) : "") + ")");
			}
			if (property.DefaultValue != null)
			{
				lines.Add("			.HasDefaultValue(" + Text.StringHelper.GenerateLiteral((dynamic)property.DefaultValue) + ")");
			}
			if (!string.IsNullOrWhiteSpace(property.DefaultValueSql))
			{
				lines.Add("			.HasDefaultValueSql(" + Text.StringHelper.DelimitString(property.DefaultValueSql) + ")");
			}
			if (!string.IsNullOrWhiteSpace(property.ComputedColumnSql))
			{
				lines.Add("			.HasComputedColumnSql(" + Text.StringHelper.DelimitString(property.ComputedColumnSql) + ")");
			}

			string propertyFluent = MultiLineFluentApi(lines.ToArray());
			if (propertyFluent != ";")
			{

            
            #line default
            #line hidden
            this.Write("\r\n\t\tentityBuilder.Property(e => e.");
            
            #line 106 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(")");
            
            #line 106 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(propertyFluent));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 107 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextModelBuilderGenerator.tt"

			}
		}

            
            #line default
            #line hidden
            this.Write("\t}\r\n\r\n\tpublic static ModelBuilder Build(ModelBuilder modelBuilder)\r\n\t\t=> modelBui" +
                    "lder.Entity<");
            
            #line 114 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextModelBuilderGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(queryEntityDesc.BaseName(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write(">(ConfigureEntity);\r\n}\r\n");
            
            #line 116 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextModelBuilderGenerator.tt"

	}

	Process();

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 121 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Model\QueryContextModelBuilderGenerator.tt"

string MultiLineFluentApi(params string[] lines)
{
	StringBuilder sb = new StringBuilder();
	if (lines != null && 0 < lines.Length)
	{
		if (lines.Length == 1)
		{
			sb.Append(lines[0].Trim());
		}
		else
		{
			foreach (var line in lines)
			{
				sb.AppendLine();
				sb.Append(line);
			}
		}
	}
	sb.Append(";");
	return sb.ToString();
}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
