// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Legion.Generators.AppGen.AppGenGenerators.Shared
{
    using Legion.Extensions;
    using Legion.Generators.AppGen.Model;
    using Legion.Generators.AppGen.Descriptors;
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Shared\EnumGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class EnumGenerator : Generator.GeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 11 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Shared\EnumGenerator.tt"

	SetGenerationEnvironment(this.GenerationEnvironment);
	
	EnumDescriptor enumDesc = GetParam<EnumDescriptor>("EnumDescriptor");
	string modelName = GetParam<string>("modelName");
	string contextName = GetParam<string>("contextName");

	StartNewFile(enumDesc.TargetFolder(modelName, contextName), enumDesc.FileName);

            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 20 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Shared\EnumGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumDesc.Namespace(modelName, contextName)));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tpublic enum ");
            
            #line 22 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Shared\EnumGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumDesc.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n");
            
            #line 24 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Shared\EnumGenerator.tt"

	var values = enumDesc.GetAllValues();
	int index = 0;
	foreach (var kvp in values)
	{
		index++;

            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 31 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Shared\EnumGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(kvp.Value));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 31 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Shared\EnumGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(kvp.Key));
            
            #line default
            #line hidden
            
            #line 31 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Shared\EnumGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(index == values.Count ? "" : ","));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 32 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Shared\EnumGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("\t}\r\n");
            
            #line 36 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Shared\EnumGenerator.tt"

	if (enumDesc.ConvertEntity == ConvertEntity.ToEnumAndEnumerationClass)
	{

            
            #line default
            #line hidden
            this.Write("\r\n\tpublic static class Extensions");
            
            #line 41 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Shared\EnumGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumDesc.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t\tpublic static Guid ToGuid(this ");
            
            #line 43 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Shared\EnumGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumDesc.Name));
            
            #line default
            #line hidden
            this.Write(" @enum)\r\n\t\t\t=> @enum switch\r\n\t\t\t{\r\n");
            
            #line 46 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Shared\EnumGenerator.tt"

	foreach (var kvp in values)
	{

            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 50 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Shared\EnumGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumDesc.Name));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 50 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Shared\EnumGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(kvp.Value));
            
            #line default
            #line hidden
            this.Write(" => ");
            
            #line 50 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Shared\EnumGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumDesc.BaseEntityname));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 50 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Shared\EnumGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(kvp.Value));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 51 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Shared\EnumGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("\t\t\t\t_ => throw new NotSupportedException($\"Invalid {nameof(");
            
            #line 54 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Shared\EnumGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(enumDesc.Name));
            
            #line default
            #line hidden
            this.Write(")} value {@enum}\"),\r\n\t\t\t};\r\n\t}\r\n");
            
            #line 57 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Shared\EnumGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 61 "C:\Code\legion\src\Legion.Generators\AppGen\AppGenGenerators\Shared\EnumGenerator.tt"

	Process();

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
