// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Legion.Generators.EqualityComparers
{
    using Legion.Extensions;
    using Legion.Generators.AppGen.Model;
    using Legion.Generators.AppGen.Descriptors;
    using Legion.Generators.AppGen.Descriptors.MetaDescriptors;
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class EqualityComparerGenerator : Generator.GeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 12 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

	SetGenerationEnvironment(this.GenerationEnvironment);
	
	EqualityComparerDescriptor equalityComparerDesc = GetParam<EqualityComparerDescriptor>("EqualityComparerDescriptor");

	StartNewFile(equalityComparerDesc.ComparerTargetFolder, equalityComparerDesc.ComparerFileName);

            
            #line default
            #line hidden
            
            #line 19 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

	if (equalityComparerDesc.IsLegionFramework)
	{

            
            #line default
            #line hidden
            this.Write("using Legion;\r\n");
            
            #line 24 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 27 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(equalityComparerDesc.ComparerBaseClassesNamespace));
            
            #line default
            #line hidden
            this.Write(";\r\nusing System.Diagnostics.CodeAnalysis;\r\n\r\n");
            
            #line 30 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

	if (equalityComparerDesc.EmbedToTargetType)
	{

            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 34 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(equalityComparerDesc.TargetTypeNamespace));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n");
            
            #line 36 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

	}
	else
	{

            
            #line default
            #line hidden
            this.Write("namespace ");
            
            #line 41 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(equalityComparerDesc.ComparerNamespace));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n");
            
            #line 43 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

	}

	if (equalityComparerDesc.EmbedToTargetType)
	{
		var classOrRecord = equalityComparerDesc.TargetType.IsRecord() ? "record" : "class";

            
            #line default
            #line hidden
            this.Write("public partial ");
            
            #line 50 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(classOrRecord));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 50 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(equalityComparerDesc.TargetTypeSimpleName));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 52 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

		PushIndent("	");
	}

            
            #line default
            #line hidden
            this.Write("public partial class ");
            
            #line 56 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(equalityComparerDesc.ComparerName));
            
            #line default
            #line hidden
            this.Write(" : IEqualityComparer<");
            
            #line 56 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(equalityComparerDesc.TargetTypeName));
            
            #line default
            #line hidden
            this.Write(">\r\n{\r\n\tpublic static bool EqualsTo(\r\n\t\t");
            
            #line 59 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(equalityComparerDesc.TargetTypeName));
            
            #line default
            #line hidden
            this.Write("? obj1,\r\n\t\t");
            
            #line 60 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(equalityComparerDesc.TargetTypeName));
            
            #line default
            #line hidden
            this.Write("? obj2,\r\n\t\tComparisonOptions comparisonOptions = ComparisonOptions.CompareAll,\r\n\t" +
                    "\tAction<ComparisonConditions<");
            
            #line 62 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(equalityComparerDesc.TargetTypeName));
            
            #line default
            #line hidden
            this.Write(">>? conditions = null,\r\n\t\tDictionary<object, HashSet<object>>? cache = null)\r\n\t{\r" +
                    "\n\t\tif (obj1 == null && obj2 == null)\r\n\t\t\treturn true;\r\n\r\n\t\tif (obj1 == null || o" +
                    "bj2 == null)\r\n\t\t\treturn false;\r\n\r\n\t\tif (ReferenceEquals(obj1, obj2))\r\n\t\t\treturn " +
                    "true;\r\n\r\n");
            
            #line 74 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

	if (equalityComparerDesc.LessThanCSharp12)
	{

            
            #line default
            #line hidden
            this.Write("\t\tcache ??= new();\r\n");
            
            #line 79 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

	}
	else
	{

            
            #line default
            #line hidden
            this.Write("\t\tcache ??= [];\r\n");
            
            #line 85 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("\r\n\t\tcache.TryGetValue(obj1, out HashSet<object>? cachedHashSet);\r\n\t\tif (cachedHas" +
                    "hSet?.Contains(obj2) == true)\r\n\t\t\treturn true;\r\n\t\t\t\r\n\t\tComparisonConditions<");
            
            #line 93 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(equalityComparerDesc.TargetTypeName));
            
            #line default
            #line hidden
            this.Write(">? conds = null;\r\n\t\t\r\n\t\tif ((ComparisonOptions.CompareProperties & comparisonOpti" +
                    "ons) == ComparisonOptions.CompareProperties)\r\n\t\t{\r\n\t\t\tif (conditions != null)\r\n\t" +
                    "\t\t{\r\n\t\t\t\tconds = new ComparisonConditions<");
            
            #line 99 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(equalityComparerDesc.TargetTypeName));
            
            #line default
            #line hidden
            this.Write(">();\r\n\t\t\t\tconditions.Invoke(conds);\r\n\r\n");
            
            #line 102 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

		List<string> notSuppoertedProperties = [];
		foreach (var property in equalityComparerDesc.ValueTypeProperties)
		{
			var notEquals = property.PropertyType == typeof(string)
				? $"!string.Equals(obj1.{property.Name}, obj2.{property.Name})"
				: $"obj1.{property.Name} != obj2.{property.Name}";

			var notSupported = string.Empty;
			if (property.IsArray())
			{
				notEquals = $"(obj1.{property.Name} != null || obj2.{property.Name} != null) && (obj1.{property.Name} == null || obj2.{property.Name} == null || !obj1.{property.Name}.SequenceEqual(obj2.{property.Name}))";
			}
			else if (property.IsDictionary())
			{
				notSupported = "//TODO: Comparer: Not supported property type >>> ";
			}
			else if (property.IsEnumerable())
			{
				notEquals = $"(obj1.{property.Name} != null || obj2.{property.Name} != null) && (obj1.{property.Name} == null || obj2.{property.Name} == null || !obj1.{property.Name}.SequenceEqual(obj2.{property.Name}))";
			}

			if (string.IsNullOrWhiteSpace(notSupported) && !property.CanRead)
				notSupported = "//TODO: Comparer: Cannot read property >>> ";

			if (!string.IsNullOrWhiteSpace(notSupported))
			{
				notSuppoertedProperties.Add($"				{notSupported}if (conds.CanCompare(obj1, nameof(obj1.{property.Name})) && {notEquals}){Environment.NewLine}				{notSupported}	obj2.{property.Name} = obj1.{property.Name}");
			}
			else
			{

            
            #line default
            #line hidden
            this.Write("\t\t\t\tif (conds.CanCompare(obj1, nameof(obj1.");
            
            #line 134 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(")) && ");
            
            #line 134 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(notEquals));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\treturn false;\r\n");
            
            #line 136 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

			}
		}
		
		foreach (var notSupported in notSuppoertedProperties)
		{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 144 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(notSupported));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 145 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

		}

            
            #line default
            #line hidden
            this.Write("\t\t\t}\r\n\t\t\telse\r\n\t\t\t{\r\n");
            
            #line 151 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

		notSuppoertedProperties = [];
		foreach (var property in equalityComparerDesc.ValueTypeProperties)
		{
			var notEquals = property.PropertyType == typeof(string)
				? $"!string.Equals(obj1.{property.Name}, obj2.{property.Name})"
				: $"obj1.{property.Name} != obj2.{property.Name}";

			var notSupported = string.Empty;
			if (property.IsArray())
			{
				notEquals = $"(obj1.{property.Name} != null || obj2.{property.Name} != null) && (obj1.{property.Name} == null || obj2.{property.Name} == null || !obj1.{property.Name}.SequenceEqual(obj2.{property.Name}))";
			}
			else if (property.IsDictionary())
			{
				notSupported = "//TODO: Comparer: Not supported property type >>> ";
			}
			else if (property.IsEnumerable())
			{
				notEquals = $"(obj1.{property.Name} != null || obj2.{property.Name} != null) && (obj1.{property.Name} == null || obj2.{property.Name} == null || !obj1.{property.Name}.SequenceEqual(obj2.{property.Name}))";
			}
			
			if (string.IsNullOrWhiteSpace(notSupported) && !property.CanRead)
				notSupported = "//TODO: Comparer: Cannot read property >>> ";

			if (!string.IsNullOrWhiteSpace(notSupported))
			{
				notSuppoertedProperties.Add($"				{notSupported}if ({notEquals}) return false;");
			}
			else
			{

            
            #line default
            #line hidden
            this.Write("\t\t\t\tif (");
            
            #line 183 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(notEquals));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\treturn false;\r\n");
            
            #line 185 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

			}
		}
		
		foreach (var notSupported in notSuppoertedProperties)
		{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 193 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(notSupported));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 194 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

		}

            
            #line default
            #line hidden
            this.Write("\t\t\t}\r\n\t\t}\r\n");
            
            #line 199 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

		if (0 < equalityComparerDesc.ValueTypeFields.Count)
		{

            
            #line default
            #line hidden
            this.Write("\r\n\t\tif ((ComparisonOptions.CompareFields & comparisonOptions) == ComparisonOption" +
                    "s.CompareFields)\r\n\t\t{\r\n\t\t\tif (conditions != null)\r\n\t\t\t{\r\n\t\t\t\tconds = new Compari" +
                    "sonConditions<");
            
            #line 208 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(equalityComparerDesc.TargetTypeName));
            
            #line default
            #line hidden
            this.Write(">();\r\n\t\t\t\tconditions.Invoke(conds);\r\n\r\n");
            
            #line 211 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

		List<string> notSuppoertedFields = [];
		foreach (var field in equalityComparerDesc.ValueTypeFields)
		{
			var notEquals = field.FieldType == typeof(string)
				? $"!string.Equals(obj1.{field.Name}, obj2.{field.Name})"
				: $"obj1.{field.Name} != obj2.{field.Name}";

			var notSupported = string.Empty;
			if (field.IsArray())
			{
				notEquals = $"(obj1.{field.Name} != null || obj2.{field.Name} != null) && (obj1.{field.Name} == null || obj2.{field.Name} == null || !obj1.{field.Name}.SequenceEqual(obj2.{field.Name}))";
			}
			else if (field.IsDictionary())
			{
				notSupported = "//TODO: Comparer: Not supported field type >>> ";
			}
			else if (field.IsEnumerable())
			{
				notEquals = $"(obj1.{field.Name} != null || obj2.{field.Name} != null) && (obj1.{field.Name} == null || obj2.{field.Name} == null || !obj1.{field.Name}.SequenceEqual(obj2.{field.Name}))";
			}

			if (!string.IsNullOrWhiteSpace(notSupported))
			{
				notSuppoertedFields.Add($"				{notSupported}if (conds.CanCompare(obj1, nameof(obj1.{field.Name})) && {notEquals}){Environment.NewLine}				{notSupported}	obj2.{field.Name} = obj1.{field.Name}");
			}
			else
			{

            
            #line default
            #line hidden
            this.Write("\t\t\t\tif (conds.CanCompare(obj1, nameof(obj1.");
            
            #line 240 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(field.Name));
            
            #line default
            #line hidden
            this.Write(")) && ");
            
            #line 240 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(notEquals));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\treturn false;\r\n");
            
            #line 242 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

			}
		}
		
		foreach (var notSupported in notSuppoertedFields)
		{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 250 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(notSupported));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 251 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

		}

            
            #line default
            #line hidden
            this.Write("\t\t\t}\r\n\t\t\telse\r\n\t\t\t{\r\n");
            
            #line 257 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

		notSuppoertedFields = [];
		foreach (var field in equalityComparerDesc.ValueTypeFields)
		{
			var notEquals = field.FieldType == typeof(string)
				? $"!string.Equals(obj1.{field.Name}, obj2.{field.Name})"
				: $"obj1.{field.Name} != obj2.{field.Name}";

			var notSupported = string.Empty;
			if (field.IsArray())
			{
				notEquals = $"(obj1.{field.Name} != null || obj2.{field.Name} != null) && (obj1.{field.Name} == null || obj2.{field.Name} == null || !obj1.{field.Name}.SequenceEqual(obj2.{field.Name}))";
			}
			else if (field.IsDictionary())
			{
				notSupported = "//TODO: Comparer: Not supported field type >>> ";
			}
			else if (field.IsEnumerable())
			{
				notEquals = $"(obj1.{field.Name} != null || obj2.{field.Name} != null) && (obj1.{field.Name} == null || obj2.{field.Name} == null || !obj1.{field.Name}.SequenceEqual(obj2.{field.Name}))";
			}

			if (!string.IsNullOrWhiteSpace(notSupported))
			{
				notSuppoertedFields.Add($"				{notSupported}if ({notEquals}) return false;");
			}
			else
			{

            
            #line default
            #line hidden
            this.Write("\t\t\t\tif (");
            
            #line 286 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(notEquals));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\treturn false;\r\n");
            
            #line 288 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

			}
		}
		
		foreach (var notSupported in notSuppoertedFields)
		{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 296 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(notSupported));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 297 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

		}

            
            #line default
            #line hidden
            this.Write("\t\t\t}\r\n\t\t}\r\n");
            
            #line 302 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

		}

            
            #line default
            #line hidden
            this.Write("\r\n\t\tif (cachedHashSet == null)\r\n\t\t{\r\n\t\t\tcachedHashSet = [];\r\n\t\t\tcache[obj1] = cac" +
                    "hedHashSet;\r\n\t\t}\r\n\r\n\t\tcachedHashSet.Add(obj2);\r\n");
            
            #line 313 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

	if (0 < equalityComparerDesc.ReferenceTypeProperties.Count || 0 < equalityComparerDesc.CollectionOfReferenceTypeProperties.Count)
	{

            
            #line default
            #line hidden
            this.Write("\r\n\t\tif ((ComparisonOptions.CompareReferences & comparisonOptions) == ComparisonOp" +
                    "tions.CompareReferences)\r\n\t\t{\r\n");
            
            #line 320 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

		notSuppoertedProperties = [];
		foreach (var navigation in equalityComparerDesc.ReferenceTypeProperties)
		{
			var notSupported = string.Empty;

			if (string.IsNullOrWhiteSpace(notSupported) && !navigation.Key.CanRead)
				notSupported = "//TODO: Comparer: Cannot read property >>> ";

			var embededNamespace = equalityComparerDesc.EmbedToTargetType
				? $"{navigation.Value.TargetTypeName}."
				: "";

			if (!string.IsNullOrWhiteSpace(notSupported))
			{
				if (equalityComparerDesc.IsComapredByReference(navigation.Key.PropertyType) == true)
				{
					notSuppoertedProperties.Add($"			{notSupported}if (!ReferenceEquals(obj2.{navigation.Key.Name}, obj1.{navigation.Key.Name})) return false;");
				}
				else
				{
					notSuppoertedProperties.Add($"			{notSupported}if (!{embededNamespace}{navigation.Value.ComparerName}.EqualsTo(obj1.{navigation.Key.Name}, obj2.{navigation.Key.Name}, comparisonOptions, conds?.GetConditions(x => x.{navigation.Key.Name}), cache)) return false;");
				}
			}
			else
			{
				if (equalityComparerDesc.IsComapredByReference(navigation.Key.PropertyType) == true)
				{

            
            #line default
            #line hidden
            this.Write("\t\t\tif (!ReferenceEquals(obj2.");
            
            #line 349 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write(", obj1.");
            
            #line 349 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write("))\r\n\t\t\t\treturn false;\r\n");
            
            #line 351 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

				}
				else
				{

            
            #line default
            #line hidden
            this.Write("\t\t\tif (!");
            
            #line 356 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(embededNamespace));
            
            #line default
            #line hidden
            
            #line 356 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Value.ComparerName));
            
            #line default
            #line hidden
            this.Write(".EqualsTo(obj1.");
            
            #line 356 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write(", obj2.");
            
            #line 356 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write(", comparisonOptions, conds?.GetConditions(x => x.");
            
            #line 356 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write("), cache))\r\n\t\t\t\treturn false;\r\n");
            
            #line 358 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

				}
			}
		}
		
		foreach (var navigation in equalityComparerDesc.CollectionOfReferenceTypeProperties)
		{
			var notSupported = string.Empty;

			if (string.IsNullOrWhiteSpace(notSupported) && !navigation.Key.CanRead)
				notSupported = "//TODO: Comparer: Cannot read property >>> ";

			var embededNamespace = equalityComparerDesc.EmbedToTargetType
				? $"{navigation.Value.TargetTypeName}."
				: "";
				
			if (!string.IsNullOrWhiteSpace(notSupported))
			{
				if (equalityComparerDesc.IsComapredByReference(navigation.Key.PropertyType) == true)
				{
					notSuppoertedProperties.Add($"			{notSupported}if (!ReferenceEquals(obj2.{navigation.Key.Name}, obj1.{navigation.Key.Name}) return false;");
				}
				else if (equalityComparerDesc.IsComapredByReference(navigation.Key.PropertyType.GetEnumerableElementType()) == true)
				{
					notSuppoertedProperties.Add($"			{notSupported}if ((obj1.{navigation.Key.Name} != null || obj2.{navigation.Key.Name} != null) && (obj1.{navigation.Key.Name} == null || obj2.{navigation.Key.Name} == null || !obj1.{navigation.Key.Name}.SequenceEqual(obj2.{navigation.Key.Name}))) return false;");
				}
				else
				{
					notSuppoertedProperties.Add($"			{notSupported}if (!ComparisonHelper.SequenceEqual(obj1.{navigation.Key.Name}, obj2.{navigation.Key.Name}, new {embededNamespace}{navigation.Value.ComparerName}(comparisonOptions, conds?.GetConditions(x => x.{navigation.Key.Name}), cache))) return false;");
				}
			}
			else
			{
				if (equalityComparerDesc.IsComapredByReference(navigation.Key.PropertyType) == true)
				{

            
            #line default
            #line hidden
            this.Write("\t\t\tif (!ReferenceEquals(obj2.");
            
            #line 394 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write(", obj1.");
            
            #line 394 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\treturn false;\r\n");
            
            #line 396 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

				}
				else if (equalityComparerDesc.IsComapredByReference(navigation.Key.PropertyType.GetEnumerableElementType()) == true)
				{

            
            #line default
            #line hidden
            this.Write("\t\t\tif ((obj1.");
            
            #line 401 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write(" != null || obj2.");
            
            #line 401 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write(" != null) && (obj1.");
            
            #line 401 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write(" == null || obj2.");
            
            #line 401 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write(" == null || !obj1.");
            
            #line 401 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write(".SequenceEqual(obj2.");
            
            #line 401 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write(")))\r\n\t\t\t\treturn false;\r\n");
            
            #line 403 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

				}
				else
				{

            
            #line default
            #line hidden
            this.Write("\t\t\tif (!ComparisonHelper.SequenceEqual(obj1.");
            
            #line 408 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write(", obj2.");
            
            #line 408 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write(", new ");
            
            #line 408 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(embededNamespace));
            
            #line default
            #line hidden
            
            #line 408 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Value.ComparerName));
            
            #line default
            #line hidden
            this.Write("(comparisonOptions, conds?.GetConditions(x => x.");
            
            #line 408 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write("), cache)))\r\n\t\t\t\treturn false;\r\n");
            
            #line 410 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

				}
			}
		}
		
		foreach (var notSupported in notSuppoertedProperties)
		{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 419 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(notSupported));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 420 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

		}

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n");
            
            #line 424 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("\r\n\t\treturn true;\r\n\t}\r\n\r\n\tpublic static int GetHashCode(\r\n\t\t");
            
            #line 432 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(equalityComparerDesc.TargetTypeName));
            
            #line default
            #line hidden
            this.Write("? obj,\r\n\t\tComparisonOptions comparisonOptions = ComparisonOptions.CompareAll,\r\n\t\t" +
                    "Action<ComparisonConditions<");
            
            #line 434 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(equalityComparerDesc.TargetTypeName));
            
            #line default
            #line hidden
            this.Write(">>? conditions = null,\r\n\t\tHashSet<object>? cache = null)\r\n\t{\r\n\t\tif (obj == null)\r" +
                    "\n\t\t\treturn 0;\r\n\r\n");
            
            #line 440 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

	if (equalityComparerDesc.LessThanCSharp12)
	{

            
            #line default
            #line hidden
            this.Write("\t\tcache ??= new();\r\n");
            
            #line 445 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

	}
	else
	{

            
            #line default
            #line hidden
            this.Write("\t\tcache ??= [];\r\n");
            
            #line 451 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("\r\n\t\tif (cache.Contains(obj))\r\n\t\t\treturn 0;\r\n\r\n");
            
            #line 458 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

		List<System.Reflection.MemberInfo> propsAndFields = equalityComparerDesc.ValueTypeProperties.Select(x => (System.Reflection.MemberInfo)x.PropertyInfo).ToList();
		propsAndFields.AddRange(equalityComparerDesc.ReferenceTypeProperties.Select(x => (System.Reflection.MemberInfo)x.Key.PropertyInfo));
		propsAndFields.AddRange(equalityComparerDesc.CollectionOfReferenceTypeProperties.Select(x => (System.Reflection.MemberInfo)x.Key.PropertyInfo));
		propsAndFields.AddRange(equalityComparerDesc.ValueTypeFields.Select(x => (System.Reflection.MemberInfo)x.FieldInfo));
		propsAndFields.AddRange(equalityComparerDesc.ReferenceTypeFields.Select(x => (System.Reflection.MemberInfo)x.Key.FieldInfo));
		propsAndFields.AddRange(equalityComparerDesc.CollectionOfReferenceTypeFields.Select(x => (System.Reflection.MemberInfo)x.Key.FieldInfo));

		var sb = new StringBuilder();
		var hash = ComputeHash(equalityComparerDesc, propsAndFields.ToArray());
		sb.AppendLine(hash);
		hash = sb.ToString();

            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 471 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(hash));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n\t\treturn hash;\r\n\t}\r\n\r\n\tpublic ComparisonOptions ComparisonOptions { get; }\r\n\t" +
                    "public Action<ComparisonConditions<");
            
            #line 477 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(equalityComparerDesc.TargetTypeName));
            
            #line default
            #line hidden
            this.Write(">>? Conditions { get; }\r\n\tpublic Dictionary<object, HashSet<object>>? Cache { get" +
                    "; }\r\n\t\r\n\tpublic ");
            
            #line 480 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(equalityComparerDesc.ComparerName));
            
            #line default
            #line hidden
            this.Write("(\r\n\t\tComparisonOptions comparisonOptions = ComparisonOptions.CompareAll,\r\n\t\tActio" +
                    "n<ComparisonConditions<");
            
            #line 482 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(equalityComparerDesc.TargetTypeName));
            
            #line default
            #line hidden
            this.Write(">>? conditions = null,\r\n\t\tDictionary<object, HashSet<object>>? cache = null)\r\n\t{\r" +
                    "\n");
            
            #line 485 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

	if (equalityComparerDesc.LessThanCSharp12)
	{

            
            #line default
            #line hidden
            this.Write("\t\tCache = cache ?? new();\r\n");
            
            #line 490 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

	}
	else
	{

            
            #line default
            #line hidden
            this.Write("\t\tCache = cache ?? [];\r\n");
            
            #line 496 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("\t\tComparisonOptions = comparisonOptions;\r\n\t\tConditions = conditions;\r\n\t}\r\n\t\r\n\tpub" +
                    "lic bool Equals(\r\n\t\t");
            
            #line 504 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(equalityComparerDesc.TargetTypeName));
            
            #line default
            #line hidden
            this.Write("? obj1,\r\n\t\t");
            
            #line 505 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(equalityComparerDesc.TargetTypeName));
            
            #line default
            #line hidden
            this.Write("? obj2)\r\n\t\t=> EqualsTo(\r\n\t\t\tobj1,\r\n\t\t\tobj2,\r\n\t\t\tComparisonOptions,\r\n\t\t\tConditions" +
                    ",\r\n\t\t\tCache);\r\n\t\r\n\tpublic int GetHashCode([DisallowNull] ");
            
            #line 513 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(equalityComparerDesc.TargetTypeName));
            
            #line default
            #line hidden
            this.Write("? obj)\r\n\t\t=> GetHashCode(\r\n\t\t\tobj,\r\n\t\t\tComparisonOptions,\r\n\t\t\tConditions,\r\n\t\t\tcac" +
                    "he: null);\r\n}\r\n");
            
            #line 520 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"


	if (equalityComparerDesc.EmbedToTargetType)
	{
		PopIndent();

            
            #line default
            #line hidden
            this.Write("}\r\n");
            
            #line 527 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

	}

	Process();

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        #line 532 "C:\Code\legion\src\Legion.Generators\EqualityComparers\EqualityComparerGenerator.tt"

string? ComputeHash(
	EqualityComparerDescriptor equalityComparerDesc,
	params System.Reflection.MemberInfo[] parameters)
{
	if (parameters == null || parameters.Length == 0)
		return "";

	var fieldsProps = new List<string>();

	for (int i = 0; i < parameters.Length; i++)
	{
		var parameter = parameters[i];
		var type = parameter.GetFieldOrPropertyType();

		if (type.IsDictionary())
			continue;

		if (type.IsSimpleType())
		{
			fieldsProps.Add($"obj.{parameter.Name}");
		}
		else if (type.IsEnumerableSimpleType())
		{
			Type itemType = type.GetEnumerableElementType();

			fieldsProps.Add($"ComparisonHelper.SequenceHashCode(obj.{parameter.Name}, System.Collections.Generic.EqualityComparer<{itemType.ToFriendlyName()}>.Default)");
		}
		else if (type.IsEnumerableType())
		{
			fieldsProps.Add($"ComparisonHelper.SequenceHashCode(obj.{parameter.Name}, System.Collections.Generic.EqualityComparer<{type.GetEnumerableElementType().FullName}>.Default)");
		}
		else //is reference type
		{
			if (equalityComparerDesc.IsComapredByReference(type))
			{
				fieldsProps.Add($"obj.{parameter.Name}?.GetHashCode()");
			}
			else
			{
				fieldsProps.Add(equalityComparerDesc.EmbedToTargetType
					? $"{type.FullName}.{type.Name}EqualityComparer.GetHashCode(obj.{parameter.Name}, comparisonOptions, /*conditions*/null, cache)"
					: $"{equalityComparerDesc.ComparerNamespace ?? type.Namespace!}.{type.Name}EqualityComparer.GetHashCode(obj.{parameter.Name}, comparisonOptions, /*conditions*/null, cache)");
			}
		}
	}

	var sb = new StringBuilder();
	var batch = fieldsProps.Take(8).ToList();
	fieldsProps = fieldsProps.Skip(8).ToList();
	var isFirst = true;
	while (batch.Any())
	{
		if (isFirst)
		{
			sb.AppendLine(batch.Count == 1
				? $"int hash = {batch[0]}?.GetHashCode() ?? 0;"
				: $"int hash = HashCode.Combine({string.Join($",{Environment.NewLine}			", batch)});");
		}
		else
		{
			sb.AppendLine($"		hash = HashCode.Combine(hash, {string.Join($",{Environment.NewLine}			", batch)});");
		}

		batch = fieldsProps.Take(7).ToList();
		fieldsProps = fieldsProps.Skip(7).ToList();
		isFirst = false;
	}

	return sb.ToString();
}

        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
