<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<LangVersion>12.0</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
		<NeutralLanguage>en</NeutralLanguage>
	</PropertyGroup>

	<Import Project="../../../SharedConfigurations.props" />

	<PropertyGroup>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<NoWarn>$(NoWarn);1591</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.9.2" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.9.2" />
		<PackageReference Include="Microsoft.VisualStudio.Threading.Analyzers" Version="17.10.48">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\src\Legion.Generators\Legion.Generators.csproj" />
		<ProjectReference Include="..\Legion.ADF.ServiceBus.PostgreSQL\Legion.ADF.ServiceBus.PostgreSQL.csproj" />
		<ProjectReference Include="..\Legion.ADF.ServiceBus.SqlServer\Legion.ADF.ServiceBus.SqlServer.csproj" />
		<!--<ProjectReference Include="..\Legion.ADF.ServiceBus.Jobs.SqlServer\Legion.ADF.ServiceBus.Jobs.SqlServer.csproj" />-->
	</ItemGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="call $(ProjectDir)\bin\$(ConfigurationName)\net8.0\Legion.ADF.ServiceBus.Generator.exe $(SolutionDir)\ADF\ServiceBus" />
	</Target>

</Project>
