GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA::devt To #TargetDbUsername#;
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA::inbox To #TargetDbUsername#;
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA::mbox To #TargetDbUsername#;
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA::outbox To #TargetDbUsername#;
GO

