<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <Import Project="../../../SharedConfigurations.props" />

  <ItemGroup>
    <ProjectReference Include="..\Legion.ADF.Audit.Abstractions\Legion.ADF.Audit.Abstractions.csproj" />
  </ItemGroup>

</Project>
