// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Legion.Generators.Mappers
{
    using Legion.Extensions;
    using Legion.Generators.AppGen.Model;
    using Legion.Generators.AppGen.Descriptors;
    using Legion.Generators.AppGen.Descriptors.MetaDescriptors;
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class TypeMapperGenerator : Generator.GeneratorBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\n");
            
            #line 12 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"

	SetGenerationEnvironment(this.GenerationEnvironment);
	
	TypeMapperDescriptor typeMapperDesc = GetParam<TypeMapperDescriptor>("TypeMapperDescriptor");

	StartNewFile(typeMapperDesc.MapperTargetFolder, typeMapperDesc.MapperFileName);

            
            #line default
            #line hidden
            
            #line 19 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"

	if (typeMapperDesc.IsLegionFramework)
	{

            
            #line default
            #line hidden
            this.Write("using Legion;\r\n");
            
            #line 24 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 27 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeMapperDesc.MapperBaseClassesNamespace));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\nnamespace ");
            
            #line 29 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeMapperDesc.MapperNamespace));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\npublic static partial class ");
            
            #line 31 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeMapperDesc.MapperName));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tpublic static ");
            
            #line 33 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeMapperDesc.TargetTypeName));
            
            #line default
            #line hidden
            this.Write("? Map(\r\n\t\t");
            
            #line 34 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeMapperDesc.SourceTypeName));
            
            #line default
            #line hidden
            this.Write(" source,\r\n\t\t");
            
            #line 35 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeMapperDesc.TargetTypeName));
            
            #line default
            #line hidden
            this.Write(" target,\r\n\t\tReferenceModifier referenceModifier = ReferenceModifier.MapAllReferen" +
                    "ces,\r\n\t\tAction<MappingConditions<");
            
            #line 37 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeMapperDesc.SourceTypeName));
            
            #line default
            #line hidden
            this.Write(">>? conditions = null,\r\n\t\tLegion.Reflection.InstanceFactory? instanceFactory = nu" +
                    "ll,\r\n\t\tDictionary<object, object>? cache = null)\r\n\t{\r\n\t\tif (source == null)\r\n\t\t\t" +
                    "return target;\r\n\r\n");
            
            #line 44 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"

	if (typeMapperDesc.LessThanCSharp12)
	{

            
            #line default
            #line hidden
            this.Write("\t\tcache ??= new();\r\n");
            
            #line 49 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"

	}
	else
	{

            
            #line default
            #line hidden
            this.Write("\t\tcache ??= [];\r\n");
            
            #line 55 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("\r\n\t\tif (cache.TryGetValue(source, out object? cached))\r\n\t\t\treturn (");
            
            #line 60 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeMapperDesc.TargetTypeName));
            
            #line default
            #line hidden
            this.Write(")cached;\r\n");
            
            #line 61 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"

	if (typeMapperDesc.TypesGeneratedByFactory?.Contains(typeMapperDesc.TargetType) == true)
	{

            
            #line default
            #line hidden
            this.Write("\r\n\t\ttarget ??= instanceFactory?.CreateInstance<");
            
            #line 66 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeMapperDesc.TargetTypeName));
            
            #line default
            #line hidden
            this.Write(">(\r\n\t\t\t\tuseActivatorIfNoFactoryFound: false,\r\n\t\t\t\tthrowIfFactoryReturnsNull: true" +
                    ")!;\r\n");
            
            #line 69 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"

	}
	else
	{

            
            #line default
            #line hidden
            this.Write("\r\n\t\ttarget ??= instanceFactory?.CreateInstance<");
            
            #line 75 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeMapperDesc.TargetTypeName));
            
            #line default
            #line hidden
            this.Write(">(\r\n\t\t\t\tuseActivatorIfNoFactoryFound: false,\r\n\t\t\t\tthrowIfFactoryReturnsNull: true" +
                    ")\r\n\t\t\t?? new ");
            
            #line 78 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeMapperDesc.TargetTypeName));
            
            #line default
            #line hidden
            this.Write("();\r\n");
            
            #line 79 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("\r\n\t\tMappingConditions<");
            
            #line 83 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeMapperDesc.SourceTypeName));
            
            #line default
            #line hidden
            this.Write(">? conds = null;\r\n\r\n\t\tif (conditions != null)\r\n\t\t{\r\n\t\t\tconds = new MappingConditi" +
                    "ons<");
            
            #line 87 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(typeMapperDesc.SourceTypeName));
            
            #line default
            #line hidden
            this.Write(">();\r\n\t\t\tconditions.Invoke(conds);\r\n\r\n");
            
            #line 90 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"

		List<string> notSuppoertedProperties = [];
		foreach (var property in typeMapperDesc.ValueTypeProperties)
		{
			var existsInSource = typeMapperDesc.ExistsInSource(property);
			var notSupported = existsInSource ? string.Empty : "//TODO: Mapper: Source property does not exists >>> ";
			var collectionCopy = string.Empty;
			if (property.IsArray())
			{
				collectionCopy = "?.ToArray()";
			}
			else if (property.IsDictionary())
			{
				notSupported = "//TODO: Mapper: Not supported target property >>> ";
				collectionCopy = "?.ToDictionary()";
			}
			else if (property.IsEnumerable())
			{
				collectionCopy = "?.ToList()";
			}

			if (string.IsNullOrWhiteSpace(notSupported) && !property.CanWrite)
				notSupported = "//TODO: Mapper: Target property is readonly >>> ";

			if (!string.IsNullOrWhiteSpace(notSupported))
			{
				notSuppoertedProperties.Add($"			{notSupported}if (conds.CanMap(source, nameof(source.{property.Name}))){Environment.NewLine}			{notSupported}	target.{property.Name} = source.{property.Name}{collectionCopy}");
			}
			else
			{

            
            #line default
            #line hidden
            this.Write("\t\t\tif (conds.CanMap(source, nameof(source.");
            
            #line 121 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(")))\r\n\t\t\t\ttarget.");
            
            #line 122 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = source.");
            
            #line 122 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            
            #line 122 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(collectionCopy));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 123 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"

			}
		}
		
		foreach (var notSupported in notSuppoertedProperties)
		{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 131 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(notSupported));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 132 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"

		}

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\t\telse\r\n\t\t{\r\n");
            
            #line 138 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"

		notSuppoertedProperties = [];
		foreach (var property in typeMapperDesc.ValueTypeProperties)
		{
			var existsInSource = typeMapperDesc.ExistsInSource(property);
			var notSupported = existsInSource ? string.Empty : "//TODO: Mapper: Source property does not exists >>> ";
			var collectionCopy = string.Empty;
			if (property.IsArray())
			{
				collectionCopy = "?.ToArray()";
			}
			else if (property.IsDictionary())
			{
				notSupported = "//TODO: Mapper: Not supported property type >>> ";
				collectionCopy = "?.ToDictionary()";
			}
			else if (property.IsEnumerable())
			{
				collectionCopy = "?.ToList()";
			}

			if (string.IsNullOrWhiteSpace(notSupported) && !property.CanWrite)
				notSupported = "//TODO: Mapper: Target property is readonly >>> ";

			if (!string.IsNullOrWhiteSpace(notSupported))
			{
				notSuppoertedProperties.Add($"			{notSupported}target.{property.Name} = source.{property.Name}{collectionCopy};");
			}
			else
			{

            
            #line default
            #line hidden
            this.Write("\t\t\ttarget.");
            
            #line 169 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = source.");
            
            #line 169 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            
            #line 169 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(collectionCopy));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 170 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"

			}
		}
		
		foreach (var notSupported in notSuppoertedProperties)
		{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 178 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(notSupported));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 179 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"

		}

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n\t\tcache.Add(source, target);\r\n");
            
            #line 185 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"

	if (0 < typeMapperDesc.ReferenceTypeProperties.Count || 0 < typeMapperDesc.CollectionOfReferenceTypeProperties.Count)
	{

            
            #line default
            #line hidden
            this.Write("\r\n\t\tif (referenceModifier == ReferenceModifier.MapAllReferences)\r\n\t\t{\r\n");
            
            #line 192 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"

		notSuppoertedProperties = [];
		foreach (var navigation in typeMapperDesc.ReferenceTypeProperties)
		{
			var existsInSource = typeMapperDesc.ExistsInSource(navigation.Key);
			var notSupported = existsInSource ? string.Empty : "//TODO: Mapper: Source property does not exists >>> ";

			if (string.IsNullOrWhiteSpace(notSupported) && !navigation.Key.CanWrite)
				notSupported = "//TODO: Mapper: Target property is readonly >>> ";

			if (!string.IsNullOrWhiteSpace(notSupported))
			{
				if (typeMapperDesc.IsComapredByReference(navigation.Key.PropertyType) == true)
				{
					notSuppoertedProperties.Add($"			{notSupported}target.{navigation.Key.Name} = source.{navigation.Key.Name};");
				}
				else
				{
					notSuppoertedProperties.Add($"			{notSupported}target.{navigation.Key.Name} = {navigation.Value.MapperName}.Map(source.{navigation.Key.Name}, target.{navigation.Key.Name}, referenceModifier, conds?.GetConditions(x => x.{navigation.Key.Name}), instanceFactory, cache)!;");
				}
			}
			else
			{
				if (typeMapperDesc.IsComapredByReference(navigation.Key.PropertyType) == true)
				{

            
            #line default
            #line hidden
            this.Write("\t\t\ttarget.");
            
            #line 218 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write(" = source.");
            
            #line 218 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 219 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"

				}
				else
				{

            
            #line default
            #line hidden
            this.Write("\t\t\ttarget.");
            
            #line 224 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 224 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Value.MapperName));
            
            #line default
            #line hidden
            this.Write(".Map(source.");
            
            #line 224 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write(", target.");
            
            #line 224 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write(", referenceModifier, conds?.GetConditions(x => x.");
            
            #line 224 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write("), instanceFactory, cache)!;\r\n");
            
            #line 225 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"

				}
			}
		}
		
		foreach (var navigation in typeMapperDesc.CollectionOfReferenceTypeProperties)
		{
			var existsInSource = typeMapperDesc.ExistsInSource(navigation.Key);
			var notSupported = existsInSource ? string.Empty : "//TODO: Mapper: Source property does not exists >>> ";

			if (string.IsNullOrWhiteSpace(notSupported) && !navigation.Key.CanWrite)
				notSupported = "//TODO: Mapper: Target property is readonly >>> ";
				
			if (!string.IsNullOrWhiteSpace(notSupported))
			{
				if (typeMapperDesc.IsComapredByReference(navigation.Key.PropertyType) == true)
				{
					notSuppoertedProperties.Add($"			{notSupported}target.{navigation.Key.Name} = source.{navigation.Key.Name};");
				}
				else if (typeMapperDesc.IsComapredByReference(navigation.Key.PropertyType.GetEnumerableElementType()) == true)
				{
					if (navigation.Key.PropertyType.IsArray)
					{
						notSuppoertedProperties.Add($"			{notSupported}target.{navigation.Key.Name} = source.{navigation.Key.Name}.ToArray();");
					}
					else
					{
						notSuppoertedProperties.Add($"			{notSupported}target.{navigation.Key.Name} = source.{navigation.Key.Name}.ToList();");
					}
				}
				else
				{
					notSuppoertedProperties.Add($"			{notSupported}target.{navigation.Key.Name} = MapperHelper.MapToList(source.{navigation.Key.Name}, target.{navigation.Key.Name}, {navigation.Value.MapperName}.Map, referenceModifier, conds?.GetConditions(x => x.{navigation.Key.Name}), instanceFactory, cache)!;");
				}
			}
			else
			{
				if (typeMapperDesc.IsComapredByReference(navigation.Key.PropertyType) == true)
				{

            
            #line default
            #line hidden
            this.Write("\t\t\ttarget.");
            
            #line 265 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write(" = source.");
            
            #line 265 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 266 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"

				}
				else if (typeMapperDesc.IsComapredByReference(navigation.Key.PropertyType.GetEnumerableElementType()) == true)
				{
					if (navigation.Key.PropertyType.IsArray)
					{

            
            #line default
            #line hidden
            this.Write("\t\t\ttarget.");
            
            #line 273 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write(" = source.");
            
            #line 273 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write(".ToArray();\r\n");
            
            #line 274 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"

					}
					else
					{

            
            #line default
            #line hidden
            this.Write("\t\t\ttarget.");
            
            #line 279 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write(" = source.");
            
            #line 279 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write(".ToList();\r\n");
            
            #line 280 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"

					}
				}
				else
				{

            
            #line default
            #line hidden
            this.Write("\t\t\ttarget.");
            
            #line 286 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write(" = MapperHelper.MapToList(source.");
            
            #line 286 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write(", target.");
            
            #line 286 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 286 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Value.MapperName));
            
            #line default
            #line hidden
            this.Write(".Map, referenceModifier, conds?.GetConditions(x => x.");
            
            #line 286 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write("), instanceFactory, cache)!;\r\n");
            
            #line 287 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"

				}
			}
		}
		
		foreach (var notSupported in notSuppoertedProperties)
		{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 296 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(notSupported));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 297 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"

		}

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\t\telse if (referenceModifier == ReferenceModifier.SetNull)\r\n\t\t{\r\n");
            
            #line 303 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"

		notSuppoertedProperties = [];
		foreach (var navigation in typeMapperDesc.ReferenceTypeProperties)
		{
			var notSupported = navigation.Key.CanWrite
				? string.Empty
				: "//TODO: Mapper: Target property is readonly >>> ";

			if (!string.IsNullOrWhiteSpace(notSupported))
			{
				notSuppoertedProperties.Add($"			{notSupported}target.{navigation.Key.Name} = null!;");
			}
			else
			{

            
            #line default
            #line hidden
            this.Write("\t\t\ttarget.");
            
            #line 318 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write(" = null!;\r\n");
            
            #line 319 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"

			}
		}

		foreach (var navigation in typeMapperDesc.CollectionOfReferenceTypeProperties)
		{
			var notSupported = navigation.Key.CanWrite
				? string.Empty
				: "//TODO: Mapper: Target property is readonly >>> ";

			if (!string.IsNullOrWhiteSpace(notSupported))
			{
				if (typeMapperDesc.LessThanCSharp12)
				{
					notSuppoertedProperties.Add($"			{notSupported}target.{navigation.Key.Name} = new();");
				}
				else
				{
					notSuppoertedProperties.Add($"			{notSupported}target.{navigation.Key.Name} = [];");
				}
			}
			else
			{
				if (typeMapperDesc.LessThanCSharp12)
				{

            
            #line default
            #line hidden
            this.Write("\t\t\ttarget.");
            
            #line 345 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write(" = new();\r\n");
            
            #line 346 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"

				}
				else
				{

            
            #line default
            #line hidden
            this.Write("\t\t\ttarget.");
            
            #line 351 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(navigation.Key.Name));
            
            #line default
            #line hidden
            this.Write(" = [];\r\n");
            
            #line 352 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"

				}
			}
		}
		
		foreach (var notSupported in notSuppoertedProperties)
		{

            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 361 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(notSupported));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 362 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"

		}

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n");
            
            #line 366 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"

	}

            
            #line default
            #line hidden
            this.Write("\r\n\t\treturn target;\r\n\t}\r\n}\r\n");
            
            #line 373 "C:\code\legion\src\Legion.Generators\Mappers\TypeMapperGenerator.tt"

	Process();

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
